#!/bin/sh
#
# Script to copy a static version of the Bacula
#  File daemon to the correct directory.
#
export LANG=C
cp -p $1 bin/bacula-fd
if [ $? != 0 ] ; then
   echo "Warning!!! $1 not found. !!!"
fi
cp -p $2 bin/  
if [ $? != 0 ] ; then
   echo "Warning!!! $2 not found. !!!"
fi
