#!/bin/sh
#
# Copy complete Bacula rescue directory to roottree 
#
host=`hostname | cut -d '.' -f 1`
cd ..
cp -a bacula roottree/bacula-${host}
if [ $? != 0 ] ; then
  echo "Build failed."
  exit 1
fi
