#!/bin/sh
#
# Script to make a static version of the Bacula
#  File daemon and to copy it to the current
#  directory.
#
export LANG=C
cwd=`pwd`
# Pretty gross
topdir=../../../..
cd $topdir
make
cd src/filed
make static-bacula-fd 2>/dev/null >/dev/null
cd $cwd       
cp -f $topdir/src/filed/static-bacula-fd bin/bacula-fd
