.\"                                      Hey, EMACS: -*- nroff -*-
.TH BTRACEBACK 8 "26 May 2006" "Kern Sibbald" "Network backup"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
 btraceback \- Produce a traceback on the event of a 'Kaboom'
.SH DESCRIPTION
.br
.SH AUTHOR
This manual page was written by Jose Luis Tallon
.nh 
<jltallon@adv\-solutions.net>.
