/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gnome.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

static GnomeUIInfo file1_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("_Connect"),
    N_("Connect to Director"),
    (gpointer) on_connect_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("_Disconnect"),
    N_("Disconnect from Director"),
    (gpointer) on_disconnect_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_SEPARATOR,
  {
    GNOME_APP_UI_ITEM, N_("E_xit"),
    NULL,
    (gpointer) on_exit_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo edit1_menu_uiinfo[] =
{
  GNOMEUIINFO_MENU_CUT_ITEM (on_cut1_activate, NULL),
  GNOMEUIINFO_MENU_COPY_ITEM (on_copy1_activate, NULL),
  GNOMEUIINFO_MENU_PASTE_ITEM (on_paste1_activate, NULL),
  GNOMEUIINFO_MENU_CLEAR_ITEM (on_clear1_activate, NULL),
  GNOMEUIINFO_END
};

static GnomeUIInfo item1_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("_Display Messages"),
    NULL,
    (gpointer) on_msgs_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo settings1_menu_uiinfo[] =
{
  GNOMEUIINFO_MENU_PREFERENCES_ITEM (on_preferences1_activate, NULL),
  GNOMEUIINFO_END
};

static GnomeUIInfo help1_menu_uiinfo[] =
{
  GNOMEUIINFO_MENU_ABOUT_ITEM (on_about_activate, NULL),
  GNOMEUIINFO_END
};

static GnomeUIInfo menubar1_uiinfo[] =
{
  GNOMEUIINFO_MENU_FILE_TREE (file1_menu_uiinfo),
  GNOMEUIINFO_MENU_EDIT_TREE (edit1_menu_uiinfo),
  GNOMEUIINFO_MENU_VIEW_TREE (item1_menu_uiinfo),
  GNOMEUIINFO_MENU_SETTINGS_TREE (settings1_menu_uiinfo),
  GNOMEUIINFO_MENU_HELP_TREE (help1_menu_uiinfo),
  GNOMEUIINFO_END
};

GtkWidget*
create_app1 (void)
{
  GtkWidget *app1;
  GtkWidget *vbox6;
  GtkWidget *handlebox1;
  GtkWidget *menubar1;
  GtkWidget *handlebox2;
  GtkWidget *toolbar2;
  GtkWidget *tmp_toolbar_icon;
  GtkWidget *connect_button1;
  GtkWidget *run_button1;
  GtkWidget *msgs_button;
  GtkWidget *restore_button;
  GtkWidget *label_button;
  GtkWidget *vbox7;
  GtkWidget *scroll1;
  GtkWidget *text1;
  GtkWidget *hbox18;
  GtkWidget *label38;
  GtkWidget *entry1;
  GtkWidget *hbox19;
  GtkWidget *frame1;
  GtkWidget *label39;
  GtkWidget *frame2;
  GtkWidget *status1;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  app1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
//  gtk_object_set_data (GTK_OBJECT (app1), "app1", app1);
  gtk_window_set_title (GTK_WINDOW (app1), _("Bacula Console"));
  gtk_window_set_position (GTK_WINDOW (app1), GTK_WIN_POS_CENTER);
//  gtk_window_set_policy (GTK_WINDOW (app1), TRUE, TRUE, TRUE);

  vbox6 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox6);
  gtk_object_set_data_full (GTK_OBJECT (app1), "vbox6", vbox6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox6);
  gtk_container_add (GTK_CONTAINER (app1), vbox6);

  handlebox1 = gtk_handle_box_new ();
  gtk_widget_ref (handlebox1);
  gtk_object_set_data_full (GTK_OBJECT (app1), "handlebox1", handlebox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (handlebox1);
  gtk_box_pack_start (GTK_BOX (vbox6), handlebox1, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (handlebox1), 1);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_ref (menubar1);
  gtk_object_set_data_full (GTK_OBJECT (app1), "menubar1", menubar1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (menubar1);
  gtk_container_add (GTK_CONTAINER (handlebox1), menubar1);
  gnome_app_fill_menu (GTK_MENU_SHELL (menubar1), menubar1_uiinfo,
                       NULL, FALSE, 0);
  gtk_menu_bar_set_shadow_type (GTK_MENU_BAR (menubar1), GTK_SHADOW_NONE);

  gtk_widget_ref (menubar1_uiinfo[0].widget);
  gtk_object_set_data_full (GTK_OBJECT (app1), "file1",
                            menubar1_uiinfo[0].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (file1_menu_uiinfo[0].widget);
  gtk_object_set_data_full (GTK_OBJECT (app1), "connect1",
                            file1_menu_uiinfo[0].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (file1_menu_uiinfo[1].widget);
  gtk_object_set_data_full (GTK_OBJECT (app1), "disconnect1",
                            file1_menu_uiinfo[1].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (file1_menu_uiinfo[2].widget);
  gtk_object_set_data_full (GTK_OBJECT (app1), "menuitem4",
                            file1_menu_uiinfo[2].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (file1_menu_uiinfo[3].widget);
  gtk_object_set_data_full (GTK_OBJECT (app1), "exit1",
                            file1_menu_uiinfo[3].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (menubar1_uiinfo[1].widget);
  gtk_object_set_data_full (GTK_OBJECT (app1), "edit1",
                            menubar1_uiinfo[1].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (edit1_menu_uiinfo[0].widget);
  gtk_object_set_data_full (GTK_OBJECT (app1), "cut1",
                            edit1_menu_uiinfo[0].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (edit1_menu_uiinfo[1].widget);
  gtk_object_set_data_full (GTK_OBJECT (app1), "copy1",
                            edit1_menu_uiinfo[1].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (edit1_menu_uiinfo[2].widget);
  gtk_object_set_data_full (GTK_OBJECT (app1), "paste1",
                            edit1_menu_uiinfo[2].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (edit1_menu_uiinfo[3].widget);
  gtk_object_set_data_full (GTK_OBJECT (app1), "clear1",
                            edit1_menu_uiinfo[3].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (edit1_menu_uiinfo[4].widget);
  gtk_object_set_data_full (GTK_OBJECT (app1), "separator1",
                            edit1_menu_uiinfo[4].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (menubar1_uiinfo[2].widget);
  gtk_object_set_data_full (GTK_OBJECT (app1), "item1",
                            menubar1_uiinfo[2].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (item1_menu_uiinfo[0].widget);
  gtk_object_set_data_full (GTK_OBJECT (app1), "msgs",
                            item1_menu_uiinfo[0].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (menubar1_uiinfo[3].widget);
  gtk_object_set_data_full (GTK_OBJECT (app1), "settings1",
                            menubar1_uiinfo[3].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (settings1_menu_uiinfo[0].widget);
  gtk_object_set_data_full (GTK_OBJECT (app1), "preferences1",
                            settings1_menu_uiinfo[0].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (menubar1_uiinfo[4].widget);
  gtk_object_set_data_full (GTK_OBJECT (app1), "help1",
                            menubar1_uiinfo[4].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (help1_menu_uiinfo[0].widget);
  gtk_object_set_data_full (GTK_OBJECT (app1), "about1",
                            help1_menu_uiinfo[0].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  handlebox2 = gtk_handle_box_new ();
  gtk_widget_ref (handlebox2);
  gtk_object_set_data_full (GTK_OBJECT (app1), "handlebox2", handlebox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (handlebox2);
  gtk_box_pack_start (GTK_BOX (vbox6), handlebox2, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (handlebox2), 1);

  toolbar2 = gtk_toolbar_new (GTK_ORIENTATION_HORIZONTAL, GTK_TOOLBAR_BOTH);
  gtk_widget_ref (toolbar2);
  gtk_object_set_data_full (GTK_OBJECT (app1), "toolbar2", toolbar2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (toolbar2);
  gtk_container_add (GTK_CONTAINER (handlebox2), toolbar2);
  gtk_container_set_border_width (GTK_CONTAINER (toolbar2), 1);
  gtk_toolbar_set_space_size (GTK_TOOLBAR (toolbar2), 16);
  gtk_toolbar_set_space_style (GTK_TOOLBAR (toolbar2), GTK_TOOLBAR_SPACE_LINE);
  gtk_toolbar_set_button_relief (GTK_TOOLBAR (toolbar2), GTK_RELIEF_NONE);

  tmp_toolbar_icon = gnome_stock_pixmap_widget (app1, GNOME_STOCK_PIXMAP_NEW);
  connect_button1 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar2),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Connect"),
                                _("Connect to Director"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (connect_button1);
  gtk_object_set_data_full (GTK_OBJECT (app1), "connect_button1", connect_button1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (connect_button1);

  tmp_toolbar_icon = gnome_stock_pixmap_widget (app1, GNOME_STOCK_PIXMAP_EXEC);
  run_button1 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar2),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Run"),
                                _("Run a Job"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (run_button1);
  gtk_object_set_data_full (GTK_OBJECT (app1), "run_button1", run_button1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (run_button1);

  tmp_toolbar_icon = gnome_stock_pixmap_widget (app1, GNOME_STOCK_PIXMAP_SEARCH);
  msgs_button = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar2),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Msgs"),
                                _("Display Messages"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (msgs_button);
  gtk_object_set_data_full (GTK_OBJECT (app1), "msgs_button", msgs_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (msgs_button);

  tmp_toolbar_icon = gnome_stock_pixmap_widget (app1, GNOME_STOCK_PIXMAP_REVERT);
  restore_button = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar2),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Restore"),
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (restore_button);
  gtk_object_set_data_full (GTK_OBJECT (app1), "restore_button", restore_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (restore_button);

  tmp_toolbar_icon = gnome_stock_pixmap_widget (app1, GNOME_STOCK_PIXMAP_SAVE_AS);
  label_button = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar2),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Label"),
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (label_button);
  gtk_object_set_data_full (GTK_OBJECT (app1), "label_button", label_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label_button);

  vbox7 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox7);
  gtk_object_set_data_full (GTK_OBJECT (app1), "vbox7", vbox7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox7);
  gtk_box_pack_start (GTK_BOX (vbox6), vbox7, TRUE, TRUE, 0);

  scroll1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scroll1);
  gtk_object_set_data_full (GTK_OBJECT (app1), "scroll1", scroll1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scroll1);
  gtk_box_pack_start (GTK_BOX (vbox7), scroll1, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scroll1), GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);

  text1 = gtk_text_new (NULL, NULL);
  gtk_widget_ref (text1);
  gtk_object_set_data_full (GTK_OBJECT (app1), "text1", text1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (text1);
  gtk_container_add (GTK_CONTAINER (scroll1), text1);
  GTK_WIDGET_UNSET_FLAGS (text1, GTK_CAN_FOCUS);

  hbox18 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox18);
  gtk_object_set_data_full (GTK_OBJECT (app1), "hbox18", hbox18,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox18);
  gtk_box_pack_start (GTK_BOX (vbox7), hbox18, FALSE, TRUE, 0);

  label38 = gtk_label_new (_(" Command: "));
  gtk_widget_ref (label38);
  gtk_object_set_data_full (GTK_OBJECT (app1), "label38", label38,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label38);
  gtk_box_pack_start (GTK_BOX (hbox18), label38, FALSE, TRUE, 0);

  entry1 = gtk_entry_new ();
  gtk_widget_ref (entry1);
  gtk_object_set_data_full (GTK_OBJECT (app1), "entry1", entry1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry1);
  gtk_box_pack_start (GTK_BOX (hbox18), entry1, TRUE, TRUE, 0);
  GTK_WIDGET_SET_FLAGS (entry1, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, entry1, _("Enter Commands Here"), NULL);

  hbox19 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox19);
  gtk_object_set_data_full (GTK_OBJECT (app1), "hbox19", hbox19,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox19);
  gtk_box_pack_start (GTK_BOX (vbox7), hbox19, FALSE, FALSE, 0);
  gtk_widget_set_usize (hbox19, -2, 22);

  frame1 = gtk_frame_new (NULL);
  gtk_widget_ref (frame1);
  gtk_object_set_data_full (GTK_OBJECT (app1), "frame1", frame1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame1);
  gtk_box_pack_start (GTK_BOX (hbox19), frame1, FALSE, TRUE, 0);
  gtk_widget_set_usize (frame1, 66, -2);
  gtk_frame_set_shadow_type (GTK_FRAME (frame1), GTK_SHADOW_IN);

  label39 = gtk_label_new (_(" Status: "));
  gtk_widget_ref (label39);
  gtk_object_set_data_full (GTK_OBJECT (app1), "label39", label39,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label39);
  gtk_container_add (GTK_CONTAINER (frame1), label39);

  frame2 = gtk_frame_new (NULL);
  gtk_widget_ref (frame2);
  gtk_object_set_data_full (GTK_OBJECT (app1), "frame2", frame2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame2);
  gtk_box_pack_start (GTK_BOX (hbox19), frame2, TRUE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame2), GTK_SHADOW_IN);

  status1 = gtk_label_new ("");
  gtk_widget_ref (status1);
  gtk_object_set_data_full (GTK_OBJECT (app1), "status1", status1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (status1);
  gtk_container_add (GTK_CONTAINER (frame2), status1);
  gtk_label_set_justify (GTK_LABEL (status1), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (status1), 0, 0.5);

  gtk_signal_connect (GTK_OBJECT (app1), "delete_event",
                      GTK_SIGNAL_FUNC (on_app1_delete_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (connect_button1), "clicked",
                      GTK_SIGNAL_FUNC (on_connect_button_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (run_button1), "clicked",
                      GTK_SIGNAL_FUNC (on_run_button_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (msgs_button), "clicked",
                      GTK_SIGNAL_FUNC (on_msgs_button_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (restore_button), "clicked",
                      GTK_SIGNAL_FUNC (on_restore_button_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (label_button), "clicked",
                      GTK_SIGNAL_FUNC (on_label_button_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (entry1), "key_press_event",
                      GTK_SIGNAL_FUNC (on_entry1_key_press_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (entry1), "key_release_event",
                      GTK_SIGNAL_FUNC (on_entry1_key_release_event),
                      NULL);

  gtk_widget_grab_focus (entry1);
  gtk_widget_grab_default (entry1);
  gtk_object_set_data (GTK_OBJECT (app1), "tooltips", tooltips);

  return app1;
}

GtkWidget*
create_about1 (void)
{
  GtkWidget *about1;
  GtkWidget *dialog_vbox5;
  GtkWidget *vbox8;
  GtkWidget *vbox9;
  GtkWidget *about_head;
  GtkWidget *hseparator1;
  GtkWidget *copyright;
  GtkWidget *authors;
  GtkWidget *theme;
  GtkWidget *dialog_action_area5;
  GtkWidget *hbox20;
  GtkWidget *label44;
  GtkWidget *about_button;

  about1 = gtk_dialog_new ();
  gtk_object_set_data (GTK_OBJECT (about1), "about1", about1);
  gtk_widget_set_usize (about1, 500, 250);
  gtk_window_set_title (GTK_WINDOW (about1), _("About Bacula Console"));
  gtk_window_set_position (GTK_WINDOW (about1), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (about1), TRUE);
  gtk_window_set_policy (GTK_WINDOW (about1), FALSE, FALSE, FALSE);

  dialog_vbox5 = GTK_DIALOG (about1)->vbox;
  gtk_object_set_data (GTK_OBJECT (about1), "dialog_vbox5", dialog_vbox5);
  gtk_widget_show (dialog_vbox5);

  vbox8 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox8);
  gtk_object_set_data_full (GTK_OBJECT (about1), "vbox8", vbox8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox8);
  gtk_box_pack_start (GTK_BOX (dialog_vbox5), vbox8, TRUE, TRUE, 0);

  vbox9 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox9);
  gtk_object_set_data_full (GTK_OBJECT (about1), "vbox9", vbox9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox9);
  gtk_box_pack_start (GTK_BOX (vbox8), vbox9, TRUE, TRUE, 0);

  about_head = gtk_label_new (_("Bacula Console 1.33 (27 February 2004)\n"));
  gtk_widget_ref (about_head);
  gtk_object_set_data_full (GTK_OBJECT (about1), "about_head", about_head,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (about_head);
  gtk_box_pack_start (GTK_BOX (vbox9), about_head, FALSE, FALSE, 0);
  gtk_widget_set_usize (about_head, -2, 102);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_ref (hseparator1);
  gtk_object_set_data_full (GTK_OBJECT (about1), "hseparator1", hseparator1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator1);
  gtk_box_pack_start (GTK_BOX (vbox9), hseparator1, FALSE, FALSE, 0);

  copyright = gtk_label_new (_("Copyright (c) 1999 - 2004, Kern Sibbald and John Walker"));
  gtk_widget_ref (copyright);
  gtk_object_set_data_full (GTK_OBJECT (about1), "copyright", copyright,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (copyright);
  gtk_box_pack_start (GTK_BOX (vbox9), copyright, TRUE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (copyright), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (copyright), 0.1, 0.5);

  authors = gtk_label_new (_("Authors: Kern Sibbald and John Walker"));
  gtk_widget_ref (authors);
  gtk_object_set_data_full (GTK_OBJECT (about1), "authors", authors,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (authors);
  gtk_box_pack_start (GTK_BOX (vbox9), authors, TRUE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (authors), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (authors), 0.0400001, 0.5);

  theme = gtk_label_new (_("It comes by night and sucks the essence from your computers"));
  gtk_widget_ref (theme);
  gtk_object_set_data_full (GTK_OBJECT (about1), "theme", theme,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (theme);
  gtk_box_pack_start (GTK_BOX (vbox9), theme, TRUE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (theme), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (theme), 0.15, 0.5);

  dialog_action_area5 = GTK_DIALOG (about1)->action_area;
  gtk_object_set_data (GTK_OBJECT (about1), "dialog_action_area5", dialog_action_area5);
  gtk_widget_show (dialog_action_area5);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_action_area5), 10);

  hbox20 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox20);
  gtk_object_set_data_full (GTK_OBJECT (about1), "hbox20", hbox20,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox20);
  gtk_box_pack_start (GTK_BOX (dialog_action_area5), hbox20, TRUE, TRUE, 0);

  label44 = gtk_label_new ("");
  gtk_widget_ref (label44);
  gtk_object_set_data_full (GTK_OBJECT (about1), "label44", label44,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label44);
  gtk_box_pack_start (GTK_BOX (hbox20), label44, TRUE, FALSE, 0);

  about_button = gnome_stock_button (GNOME_STOCK_BUTTON_OK);
  gtk_widget_ref (about_button);
  gtk_object_set_data_full (GTK_OBJECT (about1), "about_button", about_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (about_button);
  gtk_box_pack_start (GTK_BOX (hbox20), about_button, FALSE, FALSE, 0);
  gtk_widget_set_usize (about_button, 80, -2);
  gtk_container_set_border_width (GTK_CONTAINER (about_button), 1);
  GTK_WIDGET_SET_FLAGS (about_button, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (about_button), "clicked",
                      GTK_SIGNAL_FUNC (on_about_button_clicked),
                      NULL);

  return about1;
}

GtkWidget*
create_SelectDirectorDialog (void)
{
  GtkWidget *SelectDirectorDialog;
  GtkWidget *dialog_vbox6;
  GtkWidget *vbox10;
  GtkWidget *label48;
  GtkWidget *label47;
  GtkWidget *combo1;
  GtkWidget *dirselect;
  GtkWidget *dialog_action_area2;
  GtkWidget *hbox21;
  GtkWidget *button11;
  GtkWidget *label46;
  GtkWidget *button13;

  SelectDirectorDialog = gtk_dialog_new ();
  gtk_object_set_data (GTK_OBJECT (SelectDirectorDialog), "SelectDirectorDialog", SelectDirectorDialog);
  gtk_window_set_title (GTK_WINDOW (SelectDirectorDialog), _("Select Director"));
  gtk_window_set_position (GTK_WINDOW (SelectDirectorDialog), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (SelectDirectorDialog), TRUE);
  gtk_window_set_policy (GTK_WINDOW (SelectDirectorDialog), TRUE, TRUE, FALSE);

  dialog_vbox6 = GTK_DIALOG (SelectDirectorDialog)->vbox;
  gtk_object_set_data (GTK_OBJECT (SelectDirectorDialog), "dialog_vbox6", dialog_vbox6);
  gtk_widget_show (dialog_vbox6);

  vbox10 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox10);
  gtk_object_set_data_full (GTK_OBJECT (SelectDirectorDialog), "vbox10", vbox10,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox10);
  gtk_box_pack_start (GTK_BOX (dialog_vbox6), vbox10, TRUE, TRUE, 0);

  label48 = gtk_label_new ("");
  gtk_widget_ref (label48);
  gtk_object_set_data_full (GTK_OBJECT (SelectDirectorDialog), "label48", label48,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label48);
  gtk_box_pack_start (GTK_BOX (vbox10), label48, FALSE, FALSE, 0);
  gtk_widget_set_usize (label48, -2, 12);
  gtk_misc_set_alignment (GTK_MISC (label48), 0.48, 0.46);

  label47 = gtk_label_new (_("Select Director"));
  gtk_widget_ref (label47);
  gtk_object_set_data_full (GTK_OBJECT (SelectDirectorDialog), "label47", label47,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label47);
  gtk_box_pack_start (GTK_BOX (vbox10), label47, FALSE, FALSE, 0);

  combo1 = gtk_combo_new ();
  gtk_widget_ref (combo1);
  gtk_object_set_data_full (GTK_OBJECT (SelectDirectorDialog), "combo1", combo1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo1);
  gtk_box_pack_start (GTK_BOX (vbox10), combo1, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (combo1), 6);

  dirselect = GTK_COMBO (combo1)->entry;
  gtk_widget_ref (dirselect);
  gtk_object_set_data_full (GTK_OBJECT (SelectDirectorDialog), "dirselect", dirselect,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (dirselect);

  dialog_action_area2 = GTK_DIALOG (SelectDirectorDialog)->action_area;
  gtk_object_set_data (GTK_OBJECT (SelectDirectorDialog), "dialog_action_area2", dialog_action_area2);
  gtk_widget_show (dialog_action_area2);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_action_area2), 10);

  hbox21 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox21);
  gtk_object_set_data_full (GTK_OBJECT (SelectDirectorDialog), "hbox21", hbox21,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox21);
  gtk_box_pack_start (GTK_BOX (dialog_action_area2), hbox21, TRUE, TRUE, 0);

  button11 = gnome_stock_button (GNOME_STOCK_BUTTON_OK);
  gtk_widget_ref (button11);
  gtk_object_set_data_full (GTK_OBJECT (SelectDirectorDialog), "button11", button11,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button11);
  gtk_box_pack_start (GTK_BOX (hbox21), button11, FALSE, FALSE, 0);
  gtk_widget_set_usize (button11, 85, -2);

  label46 = gtk_label_new (_("         "));
  gtk_widget_ref (label46);
  gtk_object_set_data_full (GTK_OBJECT (SelectDirectorDialog), "label46", label46,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label46);
  gtk_box_pack_start (GTK_BOX (hbox21), label46, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (label46), 2, 0);

  button13 = gnome_stock_button (GNOME_STOCK_BUTTON_CANCEL);
  gtk_widget_ref (button13);
  gtk_object_set_data_full (GTK_OBJECT (SelectDirectorDialog), "button13", button13,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button13);
  gtk_box_pack_start (GTK_BOX (hbox21), button13, FALSE, FALSE, 0);

  gtk_signal_connect (GTK_OBJECT (button11), "clicked",
                      GTK_SIGNAL_FUNC (on_select_director_OK_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button13), "clicked",
                      GTK_SIGNAL_FUNC (on_select_director_cancel_clicked),
                      NULL);

  return SelectDirectorDialog;
}

GtkWidget*
create_RunDialog (void)
{
  GtkWidget *RunDialog;
  GtkWidget *dialog_vbox7;
  GtkWidget *vbox11;
  GtkWidget *vbox12;
  GtkWidget *label62;
  GtkWidget *hbox28;
  GtkWidget *hbox29;
  GtkWidget *label63;
  GtkWidget *combo_job;
  GtkWidget *entry_job;
  GtkWidget *label64;
  GtkWidget *combo_type;
  GtkWidget *entry_type;
  GtkWidget *label65;
  GtkWidget *hbox30;
  GtkWidget *label66;
  GtkWidget *combo_client;
  GtkWidget *entry_client;
  GtkWidget *label67;
  GtkWidget *hbox31;
  GtkWidget *label68;
  GtkWidget *combo_fileset;
  GtkWidget *entry_fileset;
  GtkWidget *view_fileset_button;
  GtkWidget *label69;
  GtkWidget *hbox32;
  GtkWidget *label70;
  GtkWidget *combo_level;
  GList *combo_level_items = NULL;
  GtkWidget *entry_level;
  GtkWidget *label71;
  GtkWidget *hbox33;
  GtkWidget *label72;
  GtkWidget *combo_pool;
  GList *combo_pool_items = NULL;
  GtkWidget *entry_pool;
  GtkWidget *label73;
  GtkWidget *hbox39;
  GtkWidget *label96;
  GtkWidget *combo_storage;
  GList *combo_storage_items = NULL;
  GtkWidget *entry_storage;
  GtkWidget *label97;
  GtkWidget *hbox40;
  GtkWidget *label98;
  GtkWidget *combo_messages;
  GtkWidget *entry_messages;
  GtkWidget *label99;
  GtkWidget *hbox34;
  GtkWidget *label77;
  GtkWidget *entry_where;
  GtkWidget *label78;
  GtkWidget *hbox41;
  GtkWidget *label100;
  GtkWidget *entry_when;
  GtkWidget *label101;
  GtkWidget *label84;
  GtkWidget *dialog_action_area6;
  GtkWidget *hbuttonbox1;
  GtkWidget *run_ok;
  GtkWidget *run_cancel;

  RunDialog = gtk_dialog_new ();
  gtk_object_set_data (GTK_OBJECT (RunDialog), "RunDialog", RunDialog);
  gtk_window_set_title (GTK_WINDOW (RunDialog), _("Run a Job"));
  gtk_window_set_position (GTK_WINDOW (RunDialog), GTK_WIN_POS_CENTER);
  gtk_window_set_policy (GTK_WINDOW (RunDialog), FALSE, FALSE, FALSE);

  dialog_vbox7 = GTK_DIALOG (RunDialog)->vbox;
  gtk_object_set_data (GTK_OBJECT (RunDialog), "dialog_vbox7", dialog_vbox7);
  gtk_widget_show (dialog_vbox7);

  vbox11 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox11);
  gtk_object_set_data_full (GTK_OBJECT (RunDialog), "vbox11", vbox11,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox11);
  gtk_box_pack_start (GTK_BOX (dialog_vbox7), vbox11, TRUE, TRUE, 0);

  vbox12 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox12);
  gtk_object_set_data_full (GTK_OBJECT (RunDialog), "vbox12", vbox12,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox12);
  gtk_box_pack_start (GTK_BOX (vbox11), vbox12, TRUE, TRUE, 0);

  label62 = gtk_label_new (_("Run a Job"));
  gtk_widget_ref (label62);
  gtk_object_set_data_full (GTK_OBJECT (RunDialog), "label62", label62,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label62);
  gtk_box_pack_start (GTK_BOX (vbox12), label62, FALSE, FALSE, 2);
  gtk_misc_set_padding (GTK_MISC (label62), 0, 9);

  hbox28 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox28);
  gtk_object_set_data_full (GTK_OBJECT (RunDialog), "hbox28", hbox28,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox28);
  gtk_box_pack_start (GTK_BOX (vbox12), hbox28, FALSE, FALSE, 2);

  hbox29 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox29);
  gtk_object_set_data_full (GTK_OBJECT (RunDialog), "hbox29", hbox29,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox29);
  gtk_box_pack_start (GTK_BOX (hbox28), hbox29, TRUE, TRUE, 0);

  label63 = gtk_label_new (_("Job:"));
  gtk_widget_ref (label63);
  gtk_object_set_data_full (GTK_OBJECT (RunDialog), "label63", label63,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label63);
  gtk_box_pack_start (GTK_BOX (hbox29), label63, FALSE, FALSE, 0);
  gtk_widget_set_usize (label63, 70, -2);
  gtk_label_set_justify (GTK_LABEL (label63), GTK_JUSTIFY_RIGHT);

  combo_job = gtk_combo_new ();
  gtk_widget_ref (combo_job);
  gtk_object_set_data_full (GTK_OBJECT (RunDialog), "combo_job", combo_job,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo_job);
  gtk_box_pack_start (GTK_BOX (hbox29), combo_job, TRUE, TRUE, 1);
  gtk_combo_set_value_in_list (GTK_COMBO (combo_job), TRUE, FALSE);

  entry_job = GTK_COMBO (combo_job)->entry;
  gtk_widget_ref (entry_job);
  gtk_object_set_data_full (GTK_OBJECT (RunDialog), "entry_job", entry_job,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry_job);
  gtk_entry_set_editable (GTK_ENTRY (entry_job), FALSE);

  label64 = gtk_label_new (_("   Type:"));
  gtk_widget_ref (label64);
  gtk_object_set_data_full (GTK_OBJECT (RunDialog), "label64", label64,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label64);
  gtk_box_pack_start (GTK_BOX (hbox29), label64, FALSE, FALSE, 0);

  combo_type = gtk_combo_new ();
  gtk_widget_ref (combo_type);
  gtk_object_set_data_full (GTK_OBJECT (RunDialog), "combo_type", combo_type,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo_type);
  gtk_box_pack_start (GTK_BOX (hbox29), combo_type, FALSE, FALSE, 6);
  gtk_widget_set_usize (combo_type, 131, -2);
  gtk_combo_set_value_in_list (GTK_COMBO (combo_type), TRUE, FALSE);

  entry_type = GTK_COMBO (combo_type)->entry;
  gtk_widget_ref (entry_type);
  gtk_object_set_data_full (GTK_OBJECT (RunDialog), "entry_type", entry_type,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry_type);
  gtk_widget_set_usize (entry_type, 127, -2);
  gtk_entry_set_editable (GTK_ENTRY (entry_type), FALSE);

  label65 = gtk_label_new (_(" "));
  gtk_widget_ref (label65);
  gtk_object_set_data_full (GTK_OBJECT (RunDialog), "label65", label65,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label65);
  gtk_box_pack_start (GTK_BOX (hbox28), label65, FALSE, FALSE, 30);

  hbox30 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox30);
  gtk_object_set_data_full (GTK_OBJECT (RunDialog), "hbox30", hbox30,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox30);
  gtk_box_pack_start (GTK_BOX (vbox12), hbox30, TRUE, TRUE, 0);

  label66 = gtk_label_new (_("Client:"));
  gtk_widget_ref (label66);
  gtk_object_set_data_full (GTK_OBJECT (RunDialog), "label66", label66,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label66);
  gtk_box_pack_start (GTK_BOX (hbox30), label66, FALSE, FALSE, 0);
  gtk_widget_set_usize (label66, 70, -2);
  gtk_label_set_justify (GTK_LABEL (label66), GTK_JUSTIFY_RIGHT);

  combo_client = gtk_combo_new ();
  gtk_widget_ref (combo_client);
  gtk_object_set_data_full (GTK_OBJECT (RunDialog), "combo_client", combo_client,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo_client);
  gtk_box_pack_start (GTK_BOX (hbox30), combo_client, TRUE, TRUE, 1);
  gtk_widget_set_usize (combo_client, 236, -2);
  gtk_combo_set_value_in_list (GTK_COMBO (combo_client), TRUE, FALSE);

  entry_client = GTK_COMBO (combo_client)->entry;
  gtk_widget_ref (entry_client);
  gtk_object_set_data_full (GTK_OBJECT (RunDialog), "entry_client", entry_client,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry_client);
  gtk_entry_set_editable (GTK_ENTRY (entry_client), FALSE);

  label67 = gtk_label_new (_(" "));
  gtk_widget_ref (label67);
  gtk_object_set_data_full (GTK_OBJECT (RunDialog), "label67", label67,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label67);
  gtk_box_pack_start (GTK_BOX (hbox30), label67, FALSE, FALSE, 123);

  hbox31 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox31);
  gtk_object_set_data_full (GTK_OBJECT (RunDialog), "hbox31", hbox31,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox31);
  gtk_box_pack_start (GTK_BOX (vbox12), hbox31, TRUE, TRUE, 2);

  label68 = gtk_label_new (_("FileSet: "));
  gtk_widget_ref (label68);
  gtk_object_set_data_full (GTK_OBJECT (RunDialog), "label68", label68,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label68);
  gtk_box_pack_start (GTK_BOX (hbox31), label68, FALSE, FALSE, 0);
  gtk_widget_set_usize (label68, 70, -2);
  gtk_label_set_justify (GTK_LABEL (label68), GTK_JUSTIFY_RIGHT);

  combo_fileset = gtk_combo_new ();
  gtk_widget_ref (combo_fileset);
  gtk_object_set_data_full (GTK_OBJECT (RunDialog), "combo_fileset", combo_fileset,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo_fileset);
  gtk_box_pack_start (GTK_BOX (hbox31), combo_fileset, TRUE, TRUE, 0);
  gtk_combo_set_value_in_list (GTK_COMBO (combo_fileset), TRUE, FALSE);

  entry_fileset = GTK_COMBO (combo_fileset)->entry;
  gtk_widget_ref (entry_fileset);
  gtk_object_set_data_full (GTK_OBJECT (RunDialog), "entry_fileset", entry_fileset,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry_fileset);
  gtk_entry_set_editable (GTK_ENTRY (entry_fileset), FALSE);

  view_fileset_button = gtk_button_new_with_label (_("  View FileSet  "));
  gtk_widget_ref (view_fileset_button);
  gtk_object_set_data_full (GTK_OBJECT (RunDialog), "view_fileset_button", view_fileset_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (view_fileset_button);
  gtk_box_pack_start (GTK_BOX (hbox31), view_fileset_button, FALSE, TRUE, 10);
  gtk_widget_set_usize (view_fileset_button, -2, 12);

  label69 = gtk_label_new (_("  "));
  gtk_widget_ref (label69);
  gtk_object_set_data_full (GTK_OBJECT (RunDialog), "label69", label69,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label69);
  gtk_box_pack_start (GTK_BOX (hbox31), label69, FALSE, FALSE, 65);

  hbox32 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox32);
  gtk_object_set_data_full (GTK_OBJECT (RunDialog), "hbox32", hbox32,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox32);
  gtk_box_pack_start (GTK_BOX (vbox12), hbox32, TRUE, TRUE, 2);

  label70 = gtk_label_new (_("Level:"));
  gtk_widget_ref (label70);
  gtk_object_set_data_full (GTK_OBJECT (RunDialog), "label70", label70,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label70);
  gtk_box_pack_start (GTK_BOX (hbox32), label70, FALSE, FALSE, 0);
  gtk_widget_set_usize (label70, 70, -2);
  gtk_label_set_justify (GTK_LABEL (label70), GTK_JUSTIFY_RIGHT);

  combo_level = gtk_combo_new ();
  gtk_widget_ref (combo_level);
  gtk_object_set_data_full (GTK_OBJECT (RunDialog), "combo_level", combo_level,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo_level);
  gtk_box_pack_start (GTK_BOX (hbox32), combo_level, TRUE, TRUE, 0);
  gtk_combo_set_value_in_list (GTK_COMBO (combo_level), TRUE, FALSE);
  combo_level_items = g_list_append (combo_level_items, (gpointer) "");
  gtk_combo_set_popdown_strings (GTK_COMBO (combo_level), combo_level_items);
  g_list_free (combo_level_items);

  entry_level = GTK_COMBO (combo_level)->entry;
  gtk_widget_ref (entry_level);
  gtk_object_set_data_full (GTK_OBJECT (RunDialog), "entry_level", entry_level,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry_level);
  gtk_entry_set_editable (GTK_ENTRY (entry_level), FALSE);

  label71 = gtk_label_new (_("             "));
  gtk_widget_ref (label71);
  gtk_object_set_data_full (GTK_OBJECT (RunDialog), "label71", label71,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label71);
  gtk_box_pack_start (GTK_BOX (hbox32), label71, FALSE, FALSE, 100);

  hbox33 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox33);
  gtk_object_set_data_full (GTK_OBJECT (RunDialog), "hbox33", hbox33,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox33);
  gtk_box_pack_start (GTK_BOX (vbox12), hbox33, TRUE, TRUE, 2);

  label72 = gtk_label_new (_("Pool:"));
  gtk_widget_ref (label72);
  gtk_object_set_data_full (GTK_OBJECT (RunDialog), "label72", label72,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label72);
  gtk_box_pack_start (GTK_BOX (hbox33), label72, FALSE, FALSE, 0);
  gtk_widget_set_usize (label72, 70, -2);

  combo_pool = gtk_combo_new ();
  gtk_widget_ref (combo_pool);
  gtk_object_set_data_full (GTK_OBJECT (RunDialog), "combo_pool", combo_pool,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo_pool);
  gtk_box_pack_start (GTK_BOX (hbox33), combo_pool, TRUE, TRUE, 0);
  gtk_combo_set_value_in_list (GTK_COMBO (combo_pool), TRUE, FALSE);
  combo_pool_items = g_list_append (combo_pool_items, (gpointer) "");
  gtk_combo_set_popdown_strings (GTK_COMBO (combo_pool), combo_pool_items);
  g_list_free (combo_pool_items);

  entry_pool = GTK_COMBO (combo_pool)->entry;
  gtk_widget_ref (entry_pool);
  gtk_object_set_data_full (GTK_OBJECT (RunDialog), "entry_pool", entry_pool,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry_pool);
  gtk_entry_set_editable (GTK_ENTRY (entry_pool), FALSE);

  label73 = gtk_label_new (_("   "));
  gtk_widget_ref (label73);
  gtk_object_set_data_full (GTK_OBJECT (RunDialog), "label73", label73,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label73);
  gtk_box_pack_start (GTK_BOX (hbox33), label73, FALSE, FALSE, 120);

  hbox39 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox39);
  gtk_object_set_data_full (GTK_OBJECT (RunDialog), "hbox39", hbox39,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox39);
  gtk_box_pack_start (GTK_BOX (vbox12), hbox39, TRUE, TRUE, 0);

  label96 = gtk_label_new (_("Storage:"));
  gtk_widget_ref (label96);
  gtk_object_set_data_full (GTK_OBJECT (RunDialog), "label96", label96,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label96);
  gtk_box_pack_start (GTK_BOX (hbox39), label96, FALSE, FALSE, 0);
  gtk_widget_set_usize (label96, 70, -2);

  combo_storage = gtk_combo_new ();
  gtk_widget_ref (combo_storage);
  gtk_object_set_data_full (GTK_OBJECT (RunDialog), "combo_storage", combo_storage,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo_storage);
  gtk_box_pack_start (GTK_BOX (hbox39), combo_storage, TRUE, TRUE, 0);
  gtk_combo_set_value_in_list (GTK_COMBO (combo_storage), TRUE, FALSE);
  combo_storage_items = g_list_append (combo_storage_items, (gpointer) "");
  gtk_combo_set_popdown_strings (GTK_COMBO (combo_storage), combo_storage_items);
  g_list_free (combo_storage_items);

  entry_storage = GTK_COMBO (combo_storage)->entry;
  gtk_widget_ref (entry_storage);
  gtk_object_set_data_full (GTK_OBJECT (RunDialog), "entry_storage", entry_storage,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry_storage);
  gtk_entry_set_editable (GTK_ENTRY (entry_storage), FALSE);

  label97 = gtk_label_new (_("   "));
  gtk_widget_ref (label97);
  gtk_object_set_data_full (GTK_OBJECT (RunDialog), "label97", label97,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label97);
  gtk_box_pack_start (GTK_BOX (hbox39), label97, FALSE, FALSE, 120);

  hbox40 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox40);
  gtk_object_set_data_full (GTK_OBJECT (RunDialog), "hbox40", hbox40,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox40);
  gtk_box_pack_start (GTK_BOX (vbox12), hbox40, TRUE, TRUE, 0);

  label98 = gtk_label_new (_("Messages:"));
  gtk_widget_ref (label98);
  gtk_object_set_data_full (GTK_OBJECT (RunDialog), "label98", label98,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label98);
  gtk_box_pack_start (GTK_BOX (hbox40), label98, FALSE, FALSE, 0);
  gtk_widget_set_usize (label98, 70, -2);

  combo_messages = gtk_combo_new ();
  gtk_widget_ref (combo_messages);
  gtk_object_set_data_full (GTK_OBJECT (RunDialog), "combo_messages", combo_messages,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo_messages);
  gtk_box_pack_start (GTK_BOX (hbox40), combo_messages, TRUE, TRUE, 0);
  gtk_combo_set_value_in_list (GTK_COMBO (combo_messages), TRUE, FALSE);

  entry_messages = GTK_COMBO (combo_messages)->entry;
  gtk_widget_ref (entry_messages);
  gtk_object_set_data_full (GTK_OBJECT (RunDialog), "entry_messages", entry_messages,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry_messages);
  gtk_entry_set_editable (GTK_ENTRY (entry_messages), FALSE);

  label99 = gtk_label_new (_("   "));
  gtk_widget_ref (label99);
  gtk_object_set_data_full (GTK_OBJECT (RunDialog), "label99", label99,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label99);
  gtk_box_pack_start (GTK_BOX (hbox40), label99, FALSE, FALSE, 120);

  hbox34 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox34);
  gtk_object_set_data_full (GTK_OBJECT (RunDialog), "hbox34", hbox34,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox34);
  gtk_box_pack_start (GTK_BOX (vbox12), hbox34, TRUE, TRUE, 2);

  label77 = gtk_label_new (_("Where: "));
  gtk_widget_ref (label77);
  gtk_object_set_data_full (GTK_OBJECT (RunDialog), "label77", label77,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label77);
  gtk_box_pack_start (GTK_BOX (hbox34), label77, FALSE, FALSE, 0);
  gtk_widget_set_usize (label77, 70, -2);

  entry_where = gtk_entry_new ();
  gtk_widget_ref (entry_where);
  gtk_object_set_data_full (GTK_OBJECT (RunDialog), "entry_where", entry_where,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry_where);
  gtk_box_pack_start (GTK_BOX (hbox34), entry_where, TRUE, TRUE, 0);

  label78 = gtk_label_new (_("   "));
  gtk_widget_ref (label78);
  gtk_object_set_data_full (GTK_OBJECT (RunDialog), "label78", label78,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label78);
  gtk_box_pack_start (GTK_BOX (hbox34), label78, FALSE, FALSE, 120);

  hbox41 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox41);
  gtk_object_set_data_full (GTK_OBJECT (RunDialog), "hbox41", hbox41,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox41);
  gtk_box_pack_start (GTK_BOX (vbox11), hbox41, TRUE, TRUE, 0);

  label100 = gtk_label_new (_("When:"));
  gtk_widget_ref (label100);
  gtk_object_set_data_full (GTK_OBJECT (RunDialog), "label100", label100,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label100);
  gtk_box_pack_start (GTK_BOX (hbox41), label100, FALSE, FALSE, 0);
  gtk_widget_set_usize (label100, 70, -2);

  entry_when = gtk_entry_new ();
  gtk_widget_ref (entry_when);
  gtk_object_set_data_full (GTK_OBJECT (RunDialog), "entry_when", entry_when,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry_when);
  gtk_box_pack_start (GTK_BOX (hbox41), entry_when, TRUE, TRUE, 0);

  label101 = gtk_label_new (_("   "));
  gtk_widget_ref (label101);
  gtk_object_set_data_full (GTK_OBJECT (RunDialog), "label101", label101,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label101);
  gtk_box_pack_start (GTK_BOX (hbox41), label101, FALSE, FALSE, 120);

  label84 = gtk_label_new (_("   "));
  gtk_widget_ref (label84);
  gtk_object_set_data_full (GTK_OBJECT (RunDialog), "label84", label84,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label84);
  gtk_box_pack_start (GTK_BOX (vbox11), label84, FALSE, FALSE, 0);

  dialog_action_area6 = GTK_DIALOG (RunDialog)->action_area;
  gtk_object_set_data (GTK_OBJECT (RunDialog), "dialog_action_area6", dialog_action_area6);
  gtk_widget_show (dialog_action_area6);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_action_area6), 10);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox1);
  gtk_object_set_data_full (GTK_OBJECT (RunDialog), "hbuttonbox1", hbuttonbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox1);
  gtk_box_pack_start (GTK_BOX (dialog_action_area6), hbuttonbox1, TRUE, TRUE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox1), GTK_BUTTONBOX_END);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (hbuttonbox1), 8);

  run_ok = gnome_stock_button (GNOME_STOCK_BUTTON_OK);
  gtk_widget_ref (run_ok);
  gtk_object_set_data_full (GTK_OBJECT (RunDialog), "run_ok", run_ok,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (run_ok);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), run_ok);
  GTK_WIDGET_SET_FLAGS (run_ok, GTK_CAN_DEFAULT);

  run_cancel = gnome_stock_button (GNOME_STOCK_BUTTON_CANCEL);
  gtk_widget_ref (run_cancel);
  gtk_object_set_data_full (GTK_OBJECT (RunDialog), "run_cancel", run_cancel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (run_cancel);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), run_cancel);
  GTK_WIDGET_SET_FLAGS (run_cancel, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (entry_job), "changed",
                      GTK_SIGNAL_FUNC (on_entry_job_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (view_fileset_button), "clicked",
                      GTK_SIGNAL_FUNC (on_view_fileset_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (run_ok), "clicked",
                      GTK_SIGNAL_FUNC (on_run_ok_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (run_cancel), "clicked",
                      GTK_SIGNAL_FUNC (on_run_cancel_clicked),
                      NULL);

  return RunDialog;
}

GtkWidget*
create_restore_files (void)
{
  GtkWidget *restore_files;
  GtkWidget *vbox13;
  GtkWidget *scrolledwindow4;
  GtkWidget *ctree2;
  GtkWidget *label89;
  GtkWidget *label90;
  GtkWidget *label91;
  GtkWidget *label92;
  GtkWidget *label93;
  GtkWidget *label94;
  GtkWidget *label95;
  GtkWidget *hbox38;
  GtkWidget *label88;
  GtkWidget *entry25;
  GtkWidget *hbox44;
  GtkWidget *label105;
  GtkWidget *restore_file;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  restore_files = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (restore_files), "restore_files", restore_files);
  gtk_window_set_title (GTK_WINDOW (restore_files), _("Restore File Selection"));
  gtk_window_set_position (GTK_WINDOW (restore_files), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (restore_files), TRUE);
  gtk_window_set_policy (GTK_WINDOW (restore_files), TRUE, TRUE, FALSE);

  vbox13 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox13);
  gtk_object_set_data_full (GTK_OBJECT (restore_files), "vbox13", vbox13,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox13);
  gtk_container_add (GTK_CONTAINER (restore_files), vbox13);

  scrolledwindow4 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow4);
  gtk_object_set_data_full (GTK_OBJECT (restore_files), "scrolledwindow4", scrolledwindow4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow4);
  gtk_box_pack_start (GTK_BOX (vbox13), scrolledwindow4, TRUE, TRUE, 0);

  ctree2 = gtk_ctree_new (7, 0);
  gtk_widget_ref (ctree2);
  gtk_object_set_data_full (GTK_OBJECT (restore_files), "ctree2", ctree2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (ctree2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow4), ctree2);
  gtk_clist_set_column_width (GTK_CLIST (ctree2), 0, 55);
  gtk_clist_set_column_width (GTK_CLIST (ctree2), 1, 246);
  gtk_clist_set_column_width (GTK_CLIST (ctree2), 2, 67);
  gtk_clist_set_column_width (GTK_CLIST (ctree2), 3, 80);
  gtk_clist_set_column_width (GTK_CLIST (ctree2), 4, 80);
  gtk_clist_set_column_width (GTK_CLIST (ctree2), 5, 80);
  gtk_clist_set_column_width (GTK_CLIST (ctree2), 6, 80);
  gtk_clist_column_titles_show (GTK_CLIST (ctree2));

  label89 = gtk_label_new (_("Type"));
  gtk_widget_ref (label89);
  gtk_object_set_data_full (GTK_OBJECT (restore_files), "label89", label89,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label89);
  gtk_clist_set_column_widget (GTK_CLIST (ctree2), 0, label89);

  label90 = gtk_label_new (_("Filename"));
  gtk_widget_ref (label90);
  gtk_object_set_data_full (GTK_OBJECT (restore_files), "label90", label90,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label90);
  gtk_clist_set_column_widget (GTK_CLIST (ctree2), 1, label90);

  label91 = gtk_label_new (_("Permissions"));
  gtk_widget_ref (label91);
  gtk_object_set_data_full (GTK_OBJECT (restore_files), "label91", label91,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label91);
  gtk_clist_set_column_widget (GTK_CLIST (ctree2), 2, label91);

  label92 = gtk_label_new (_("User"));
  gtk_widget_ref (label92);
  gtk_object_set_data_full (GTK_OBJECT (restore_files), "label92", label92,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label92);
  gtk_clist_set_column_widget (GTK_CLIST (ctree2), 3, label92);

  label93 = gtk_label_new (_("Group"));
  gtk_widget_ref (label93);
  gtk_object_set_data_full (GTK_OBJECT (restore_files), "label93", label93,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label93);
  gtk_clist_set_column_widget (GTK_CLIST (ctree2), 4, label93);

  label94 = gtk_label_new (_("Size"));
  gtk_widget_ref (label94);
  gtk_object_set_data_full (GTK_OBJECT (restore_files), "label94", label94,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label94);
  gtk_clist_set_column_widget (GTK_CLIST (ctree2), 5, label94);

  label95 = gtk_label_new (_("Date"));
  gtk_widget_ref (label95);
  gtk_object_set_data_full (GTK_OBJECT (restore_files), "label95", label95,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label95);
  gtk_clist_set_column_widget (GTK_CLIST (ctree2), 6, label95);

  hbox38 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox38);
  gtk_object_set_data_full (GTK_OBJECT (restore_files), "hbox38", hbox38,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox38);
  gtk_box_pack_start (GTK_BOX (vbox13), hbox38, FALSE, TRUE, 0);

  label88 = gtk_label_new (_(" cwd:"));
  gtk_widget_ref (label88);
  gtk_object_set_data_full (GTK_OBJECT (restore_files), "label88", label88,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label88);
  gtk_box_pack_start (GTK_BOX (hbox38), label88, FALSE, TRUE, 0);

  entry25 = gtk_entry_new ();
  gtk_widget_ref (entry25);
  gtk_object_set_data_full (GTK_OBJECT (restore_files), "entry25", entry25,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry25);
  gtk_box_pack_start (GTK_BOX (hbox38), entry25, TRUE, TRUE, 0);
  GTK_WIDGET_SET_FLAGS (entry25, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, entry25, _("Enter Commands Here"), NULL);

  hbox44 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox44);
  gtk_object_set_data_full (GTK_OBJECT (restore_files), "hbox44", hbox44,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox44);
  gtk_box_pack_start (GTK_BOX (vbox13), hbox44, FALSE, TRUE, 0);

  label105 = gtk_label_new (_(" "));
  gtk_widget_ref (label105);
  gtk_object_set_data_full (GTK_OBJECT (restore_files), "label105", label105,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label105);
  gtk_box_pack_start (GTK_BOX (hbox44), label105, TRUE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label105), GTK_JUSTIFY_FILL);
  gtk_misc_set_padding (GTK_MISC (label105), 59, 0);

  restore_file = gnome_stock_button (GNOME_STOCK_BUTTON_OK);
  gtk_widget_ref (restore_file);
  gtk_object_set_data_full (GTK_OBJECT (restore_files), "restore_file", restore_file,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (restore_file);
  gtk_box_pack_start (GTK_BOX (hbox44), restore_file, TRUE, FALSE, 0);
  gtk_widget_set_usize (restore_file, 108, 47);
  gtk_container_set_border_width (GTK_CONTAINER (restore_file), 9);

  gtk_signal_connect (GTK_OBJECT (entry25), "key_press_event",
                      GTK_SIGNAL_FUNC (on_entry1_key_press_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (entry25), "key_release_event",
                      GTK_SIGNAL_FUNC (on_entry1_key_release_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (restore_file), "clicked",
                      GTK_SIGNAL_FUNC (on_restore_file_clicked),
                      NULL);

  gtk_widget_grab_focus (entry25);
  gtk_widget_grab_default (entry25);
  gtk_object_set_data (GTK_OBJECT (restore_files), "tooltips", tooltips);

  return restore_files;
}

GtkWidget*
create_restore_dialog (void)
{
  GtkWidget *restore_dialog;
  GtkWidget *dialog_vbox8;
  GtkWidget *hbox42;
  GtkWidget *frame3;
  GtkWidget *hbox43;
  GtkWidget *label102;
  GtkWidget *vbox15;
  GtkWidget *label103;
  GSList *vbox15_group = NULL;
  GtkWidget *rb_most_recent;
  GtkWidget *rb_jobs;
  GtkWidget *rb_file;
  GtkWidget *label104;
  GtkWidget *vbox14;
  GtkWidget *apply_button;
  GtkWidget *dialog_action_area7;
  GtkWidget *hbuttonbox2;
  GtkWidget *restore_ok;
  GtkWidget *restore_cancel;

  restore_dialog = gtk_dialog_new ();
  gtk_object_set_data (GTK_OBJECT (restore_dialog), "restore_dialog", restore_dialog);
  gtk_window_set_title (GTK_WINDOW (restore_dialog), _("Restore Files"));
  gtk_window_set_position (GTK_WINDOW (restore_dialog), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (restore_dialog), TRUE);
  gtk_window_set_policy (GTK_WINDOW (restore_dialog), FALSE, FALSE, FALSE);

  dialog_vbox8 = GTK_DIALOG (restore_dialog)->vbox;
  gtk_object_set_data (GTK_OBJECT (restore_dialog), "dialog_vbox8", dialog_vbox8);
  gtk_widget_show (dialog_vbox8);

  hbox42 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox42);
  gtk_object_set_data_full (GTK_OBJECT (restore_dialog), "hbox42", hbox42,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox42);
  gtk_box_pack_start (GTK_BOX (dialog_vbox8), hbox42, TRUE, TRUE, 0);

  frame3 = gtk_frame_new (_("Select by:"));
  gtk_widget_ref (frame3);
  gtk_object_set_data_full (GTK_OBJECT (restore_dialog), "frame3", frame3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame3);
  gtk_box_pack_start (GTK_BOX (hbox42), frame3, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame3), 8);

  hbox43 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox43);
  gtk_object_set_data_full (GTK_OBJECT (restore_dialog), "hbox43", hbox43,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox43);
  gtk_container_add (GTK_CONTAINER (frame3), hbox43);

  label102 = gtk_label_new (_("         "));
  gtk_widget_ref (label102);
  gtk_object_set_data_full (GTK_OBJECT (restore_dialog), "label102", label102,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label102);
  gtk_box_pack_end (GTK_BOX (hbox43), label102, FALSE, FALSE, 0);

  vbox15 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox15);
  gtk_object_set_data_full (GTK_OBJECT (restore_dialog), "vbox15", vbox15,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox15);
  gtk_box_pack_start (GTK_BOX (hbox43), vbox15, TRUE, TRUE, 0);

  label103 = gtk_label_new ("");
  gtk_widget_ref (label103);
  gtk_object_set_data_full (GTK_OBJECT (restore_dialog), "label103", label103,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label103);
  gtk_box_pack_start (GTK_BOX (vbox15), label103, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (label103), 0, 2);

  rb_most_recent = gtk_radio_button_new_with_label (vbox15_group, _("Select most recent backup"));
  vbox15_group = gtk_radio_button_group (GTK_RADIO_BUTTON (rb_most_recent));
  gtk_widget_ref (rb_most_recent);
  gtk_object_set_data_full (GTK_OBJECT (restore_dialog), "rb_most_recent", rb_most_recent,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (rb_most_recent);
  gtk_box_pack_start (GTK_BOX (vbox15), rb_most_recent, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (rb_most_recent), 3);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (rb_most_recent), TRUE);

  rb_jobs = gtk_radio_button_new_with_label (vbox15_group, _("Select list of Jobs"));
  vbox15_group = gtk_radio_button_group (GTK_RADIO_BUTTON (rb_jobs));
  gtk_widget_ref (rb_jobs);
  gtk_object_set_data_full (GTK_OBJECT (restore_dialog), "rb_jobs", rb_jobs,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (rb_jobs);
  gtk_box_pack_start (GTK_BOX (vbox15), rb_jobs, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (rb_jobs), 5);

  rb_file = gtk_radio_button_new_with_label (vbox15_group, _("Find a specific file"));
  vbox15_group = gtk_radio_button_group (GTK_RADIO_BUTTON (rb_file));
  gtk_widget_ref (rb_file);
  gtk_object_set_data_full (GTK_OBJECT (restore_dialog), "rb_file", rb_file,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (rb_file);
  gtk_box_pack_start (GTK_BOX (vbox15), rb_file, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (rb_file), 4);

  label104 = gtk_label_new ("");
  gtk_widget_ref (label104);
  gtk_object_set_data_full (GTK_OBJECT (restore_dialog), "label104", label104,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label104);
  gtk_box_pack_start (GTK_BOX (vbox15), label104, FALSE, FALSE, 0);

  vbox14 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox14);
  gtk_object_set_data_full (GTK_OBJECT (restore_dialog), "vbox14", vbox14,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox14);
  gtk_box_pack_start (GTK_BOX (hbox42), vbox14, FALSE, FALSE, 0);

  apply_button = gnome_stock_button (GNOME_STOCK_BUTTON_APPLY);
  gtk_widget_ref (apply_button);
  gtk_object_set_data_full (GTK_OBJECT (restore_dialog), "apply_button", apply_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (apply_button);
  gtk_box_pack_start (GTK_BOX (vbox14), apply_button, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (apply_button), 50);

  dialog_action_area7 = GTK_DIALOG (restore_dialog)->action_area;
  gtk_object_set_data (GTK_OBJECT (restore_dialog), "dialog_action_area7", dialog_action_area7);
  gtk_widget_show (dialog_action_area7);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_action_area7), 10);

  hbuttonbox2 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox2);
  gtk_object_set_data_full (GTK_OBJECT (restore_dialog), "hbuttonbox2", hbuttonbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox2);
  gtk_box_pack_start (GTK_BOX (dialog_action_area7), hbuttonbox2, TRUE, TRUE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox2), GTK_BUTTONBOX_END);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (hbuttonbox2), 8);

  restore_ok = gnome_stock_button (GNOME_STOCK_BUTTON_OK);
  gtk_widget_ref (restore_ok);
  gtk_object_set_data_full (GTK_OBJECT (restore_dialog), "restore_ok", restore_ok,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (restore_ok);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), restore_ok);
  GTK_WIDGET_SET_FLAGS (restore_ok, GTK_CAN_DEFAULT);

  restore_cancel = gnome_stock_button (GNOME_STOCK_BUTTON_CANCEL);
  gtk_widget_ref (restore_cancel);
  gtk_object_set_data_full (GTK_OBJECT (restore_dialog), "restore_cancel", restore_cancel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (restore_cancel);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), restore_cancel);
  GTK_WIDGET_SET_FLAGS (restore_cancel, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (apply_button), "clicked",
                      GTK_SIGNAL_FUNC (on_apply_button_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (restore_ok), "clicked",
                      GTK_SIGNAL_FUNC (on_restore_ok_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (restore_cancel), "clicked",
                      GTK_SIGNAL_FUNC (on_restore_cancel_clicked),
                      NULL);

  return restore_dialog;
}

GtkWidget*
create_label_dialog (void)
{
  GtkWidget *label_dialog;
  GtkWidget *dialog_vbox9;
  GtkWidget *vbox16;
  GtkWidget *label106;
  GtkWidget *hbox45;
  GtkWidget *label107;
  GtkWidget *label_combo_storage;
  GList *label_combo_storage_items = NULL;
  GtkWidget *entry26;
  GtkWidget *hbox46;
  GtkWidget *label109;
  GtkWidget *label_combo_pool;
  GList *label_combo_pool_items = NULL;
  GtkWidget *entry27;
  GtkWidget *hbox47;
  GtkWidget *label111;
  GtkWidget *label_entry_volume;
  GtkWidget *hbox48;
  GtkWidget *slot1;
  GtkObject *label_slot_adj;
  GtkWidget *label_slot;
  GtkWidget *label113;
  GtkWidget *dialog_action_area8;
  GtkWidget *hbuttonbox3;
  GtkWidget *label_ok;
  GtkWidget *label_cancel;

  label_dialog = gtk_dialog_new ();
  gtk_object_set_data (GTK_OBJECT (label_dialog), "label_dialog", label_dialog);
  gtk_window_set_title (GTK_WINDOW (label_dialog), _("Label a Volume"));
  gtk_window_set_position (GTK_WINDOW (label_dialog), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (label_dialog), TRUE);
  gtk_window_set_policy (GTK_WINDOW (label_dialog), FALSE, FALSE, TRUE);

  dialog_vbox9 = GTK_DIALOG (label_dialog)->vbox;
  gtk_object_set_data (GTK_OBJECT (label_dialog), "dialog_vbox9", dialog_vbox9);
  gtk_widget_show (dialog_vbox9);

  vbox16 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox16);
  gtk_object_set_data_full (GTK_OBJECT (label_dialog), "vbox16", vbox16,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox16);
  gtk_box_pack_start (GTK_BOX (dialog_vbox9), vbox16, FALSE, TRUE, 0);

  label106 = gtk_label_new (_("Label a Volume"));
  gtk_widget_ref (label106);
  gtk_object_set_data_full (GTK_OBJECT (label_dialog), "label106", label106,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label106);
  gtk_box_pack_start (GTK_BOX (vbox16), label106, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (label106), 0, 9);

  hbox45 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox45);
  gtk_object_set_data_full (GTK_OBJECT (label_dialog), "hbox45", hbox45,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox45);
  gtk_box_pack_start (GTK_BOX (vbox16), hbox45, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox45), 5);

  label107 = gtk_label_new (_("Storage:"));
  gtk_widget_ref (label107);
  gtk_object_set_data_full (GTK_OBJECT (label_dialog), "label107", label107,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label107);
  gtk_box_pack_start (GTK_BOX (hbox45), label107, TRUE, TRUE, 0);
  gtk_widget_set_usize (label107, 78, -2);
  gtk_misc_set_alignment (GTK_MISC (label107), 0.15, 0.5);

  label_combo_storage = gtk_combo_new ();
  gtk_widget_ref (label_combo_storage);
  gtk_object_set_data_full (GTK_OBJECT (label_dialog), "label_combo_storage", label_combo_storage,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label_combo_storage);
  gtk_box_pack_start (GTK_BOX (hbox45), label_combo_storage, TRUE, TRUE, 15);
  gtk_combo_set_value_in_list (GTK_COMBO (label_combo_storage), TRUE, FALSE);
  label_combo_storage_items = g_list_append (label_combo_storage_items, (gpointer) "");
  gtk_combo_set_popdown_strings (GTK_COMBO (label_combo_storage), label_combo_storage_items);
  g_list_free (label_combo_storage_items);

  entry26 = GTK_COMBO (label_combo_storage)->entry;
  gtk_widget_ref (entry26);
  gtk_object_set_data_full (GTK_OBJECT (label_dialog), "entry26", entry26,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry26);
  gtk_entry_set_editable (GTK_ENTRY (entry26), FALSE);

  hbox46 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox46);
  gtk_object_set_data_full (GTK_OBJECT (label_dialog), "hbox46", hbox46,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox46);
  gtk_box_pack_start (GTK_BOX (vbox16), hbox46, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox46), 5);

  label109 = gtk_label_new (_("Pool:"));
  gtk_widget_ref (label109);
  gtk_object_set_data_full (GTK_OBJECT (label_dialog), "label109", label109,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label109);
  gtk_box_pack_start (GTK_BOX (hbox46), label109, TRUE, TRUE, 0);
  gtk_widget_set_usize (label109, 78, -2);
  gtk_label_set_justify (GTK_LABEL (label109), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label109), 0.12, 0.5);

  label_combo_pool = gtk_combo_new ();
  gtk_widget_ref (label_combo_pool);
  gtk_object_set_data_full (GTK_OBJECT (label_dialog), "label_combo_pool", label_combo_pool,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label_combo_pool);
  gtk_box_pack_start (GTK_BOX (hbox46), label_combo_pool, TRUE, TRUE, 14);
  gtk_combo_set_value_in_list (GTK_COMBO (label_combo_pool), TRUE, FALSE);
  label_combo_pool_items = g_list_append (label_combo_pool_items, (gpointer) "");
  gtk_combo_set_popdown_strings (GTK_COMBO (label_combo_pool), label_combo_pool_items);
  g_list_free (label_combo_pool_items);

  entry27 = GTK_COMBO (label_combo_pool)->entry;
  gtk_widget_ref (entry27);
  gtk_object_set_data_full (GTK_OBJECT (label_dialog), "entry27", entry27,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry27);
  gtk_entry_set_editable (GTK_ENTRY (entry27), FALSE);

  hbox47 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox47);
  gtk_object_set_data_full (GTK_OBJECT (label_dialog), "hbox47", hbox47,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox47);
  gtk_box_pack_start (GTK_BOX (vbox16), hbox47, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox47), 5);

  label111 = gtk_label_new (_("Volume Name:"));
  gtk_widget_ref (label111);
  gtk_object_set_data_full (GTK_OBJECT (label_dialog), "label111", label111,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label111);
  gtk_box_pack_start (GTK_BOX (hbox47), label111, TRUE, TRUE, 0);
  gtk_widget_set_usize (label111, 78, -2);
  gtk_label_set_justify (GTK_LABEL (label111), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label111), 0.17, 0.5);

  label_entry_volume = gtk_entry_new ();
  gtk_widget_ref (label_entry_volume);
  gtk_object_set_data_full (GTK_OBJECT (label_dialog), "label_entry_volume", label_entry_volume,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label_entry_volume);
  gtk_box_pack_start (GTK_BOX (hbox47), label_entry_volume, TRUE, TRUE, 0);

  hbox48 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox48);
  gtk_object_set_data_full (GTK_OBJECT (label_dialog), "hbox48", hbox48,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox48);
  gtk_box_pack_start (GTK_BOX (vbox16), hbox48, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox48), 5);

  slot1 = gtk_label_new (_("Slot:"));
  gtk_widget_ref (slot1);
  gtk_object_set_data_full (GTK_OBJECT (label_dialog), "slot1", slot1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (slot1);
  gtk_box_pack_start (GTK_BOX (hbox48), slot1, FALSE, TRUE, 0);
  gtk_widget_set_usize (slot1, 93, -2);
  gtk_label_set_justify (GTK_LABEL (slot1), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (slot1), 0.09, 0.5);

  label_slot_adj = gtk_adjustment_new (0, 0, 10000, 1, 10, 10);
  label_slot = gtk_spin_button_new (GTK_ADJUSTMENT (label_slot_adj), 1, 0);
  gtk_widget_ref (label_slot);
  gtk_object_set_data_full (GTK_OBJECT (label_dialog), "label_slot", label_slot,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label_slot);
  gtk_box_pack_start (GTK_BOX (hbox48), label_slot, TRUE, TRUE, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (label_slot), TRUE);

  label113 = gtk_label_new (_("   "));
  gtk_widget_ref (label113);
  gtk_object_set_data_full (GTK_OBJECT (label_dialog), "label113", label113,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label113);
  gtk_box_pack_start (GTK_BOX (vbox16), label113, FALSE, FALSE, 0);

  dialog_action_area8 = GTK_DIALOG (label_dialog)->action_area;
  gtk_object_set_data (GTK_OBJECT (label_dialog), "dialog_action_area8", dialog_action_area8);
  gtk_widget_show (dialog_action_area8);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_action_area8), 10);

  hbuttonbox3 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox3);
  gtk_object_set_data_full (GTK_OBJECT (label_dialog), "hbuttonbox3", hbuttonbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox3);
  gtk_box_pack_start (GTK_BOX (dialog_action_area8), hbuttonbox3, TRUE, TRUE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox3), GTK_BUTTONBOX_END);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (hbuttonbox3), 8);

  label_ok = gnome_stock_button (GNOME_STOCK_BUTTON_OK);
  gtk_widget_ref (label_ok);
  gtk_object_set_data_full (GTK_OBJECT (label_dialog), "label_ok", label_ok,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label_ok);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), label_ok);
  GTK_WIDGET_SET_FLAGS (label_ok, GTK_CAN_DEFAULT);

  label_cancel = gnome_stock_button (GNOME_STOCK_BUTTON_CANCEL);
  gtk_widget_ref (label_cancel);
  gtk_object_set_data_full (GTK_OBJECT (label_dialog), "label_cancel", label_cancel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label_cancel);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), label_cancel);
  GTK_WIDGET_SET_FLAGS (label_cancel, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (label_ok), "clicked",
                      GTK_SIGNAL_FUNC (on_label_ok_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (label_cancel), "clicked",
                      GTK_SIGNAL_FUNC (on_label_cancel_clicked),
                      NULL);

  return label_dialog;
}

