/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_app1 (void);
GtkWidget* create_about1 (void);
GtkWidget* create_SelectDirectorDialog (void);
GtkWidget* create_RunDialog (void);
GtkWidget* create_restore_files (void);
GtkWidget* create_restore_dialog (void);
GtkWidget* create_label_dialog (void);
