#!/bin/sh
echo "Creating bacula-doc.tar.gz"
tar cfz bacula-doc.tar.gz bacula
echo "Copying tar file, manual, and pdf to Bacula Web site"
sudo cp bacula-doc.tar.gz /mnt/matou/home/www/bacula/public/docs/
sudo rm -rf /mnt/matou/home/www/bacula/public/docs/html-manual
sudo mkdir -p /mnt/matou/home/www/bacula/public/docs/html-manual
sudo cp -af bacula/* /mnt/matou/home/www/bacula/public/docs/html-manual/
sudo cp -f bacula.pdf /mnt/matou/home/www/bacula/public/docs/
echo "Removing local copy of tar file"
rm bacula-doc.tar.gz
