#!/bin/sh

ftp -i ftp.sectoor.de <<END_OF_DATA
cd www/htdocs/dev-manual
lcd /home/kern/bacula/k/doc/latex/bacula
mput *
cd ../html-manual
put faq.html
put Conf-Diagram.png
cd ..
lcd ..
put bacula.pdf dev-bacula.pdf
quit
END_OF_DATA
