#!/bin/sh
#
# Script to make a static version of the Bacula
#  File daemon and to copy it to the current
#  directory.
#
cwd=`pwd`
cd ../..
make
cd src/filed
make static-bacula-fd
cd $cwd       
cp -f ../../src/filed/static-bacula-fd bacula-fd
cp ../../src/filed/bacula-fd.conf bacula-fd.conf
