#!/bin/sh
#
#  Make the stupid bacula.def file so that we don't have to do it
#    manually
#
#  Kern Sibbald, June 2007
#

if test -f ../../../../../cross-tools/mingw32/mingw32/bin/nm; then
 NM=../../../../../cross-tools/mingw32/mingw32/bin/nm
else
 NM=../../../../cross-tools/mingw32/mingw32/bin/nm
fi
 
echo "LIBRARY bacula.dll"
echo "EXPORTS"
echo " "

for i in *.o ; do \
   echo "; $i"; \
   ${NM} $i | grep "^[0-9a-f]* T _" | cut -c13- ; \
   echo " "; \
done
