/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <bonobo.h>
#include <gnome.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

static GnomeUIInfo file1_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("_Connect"),
    N_("Connect to Director"),
    (gpointer) on_connect_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("_Disconnect"),
    N_("Disconnect from Director"),
    (gpointer) on_disconnect_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_SEPARATOR,
  {
    GNOME_APP_UI_ITEM, N_("gtk-quit"),
    NULL,
    (gpointer) on_exit_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo edit1_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("gtk-cut"),
    NULL,
    (gpointer) on_cut1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("gtk-copy"),
    NULL,
    (gpointer) on_copy1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("gtk-paste"),
    NULL,
    (gpointer) on_paste1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("gtk-clear"),
    NULL,
    (gpointer) on_clear1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_SEPARATOR,
  GNOMEUIINFO_END
};

static GnomeUIInfo item1_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("_Display Messages"),
    NULL,
    (gpointer) on_msgs_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo settings1_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("gtk-preferences"),
    NULL,
    (gpointer) on_preferences1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo help1_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("gnome-stock-about"),
    NULL,
    (gpointer) on_about_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo menubar1_uiinfo[] =
{
  {
    GNOME_APP_UI_SUBTREE, N_("_File"),
    NULL,
    file1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_SUBTREE, N_("_Edit"),
    NULL,
    edit1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_SUBTREE, N_("_View"),
    N_("Display Messages"),
    item1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_SUBTREE, N_("_Settings"),
    NULL,
    settings1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_SUBTREE, N_("_Help"),
    NULL,
    help1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

GtkWidget*
create_console (void)
{
  GtkWidget *console;
  GtkWidget *vbox6;
  GtkWidget *handlebox1;
  GtkWidget *menubar1;
  GtkWidget *handlebox2;
  GtkWidget *toolbar2;
  GtkIconSize tmp_toolbar_icon_size;
  GtkWidget *tmp_image;
  GtkWidget *connect_button1;
  GtkWidget *run_button1;
  GtkWidget *dir_button;
  GtkWidget *restore_button;
  GtkWidget *label_button;
  GtkWidget *msgs_button;
  GtkWidget *vbox7;
  GtkWidget *scroll1;
  GtkWidget *text1;
  GtkWidget *hbox18;
  GtkWidget *label38;
  GtkWidget *entry1;
  GtkWidget *hbox19;
  GtkWidget *frame1;
  GtkWidget *label39;
  GtkWidget *frame2;
  GtkWidget *status1;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  console = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (console), _("Bacula Console"));
  gtk_window_set_position (GTK_WINDOW (console), GTK_WIN_POS_CENTER);
  gtk_window_set_default_size (GTK_WINDOW (console), 700, 600);

  vbox6 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox6);
  gtk_container_add (GTK_CONTAINER (console), vbox6);

  handlebox1 = gtk_handle_box_new ();
  gtk_widget_show (handlebox1);
  gtk_box_pack_start (GTK_BOX (vbox6), handlebox1, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (handlebox1), 1);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_show (menubar1);
  gtk_container_add (GTK_CONTAINER (handlebox1), menubar1);
  gnome_app_fill_menu (GTK_MENU_SHELL (menubar1), menubar1_uiinfo,
                       accel_group, FALSE, 0);

  handlebox2 = gtk_handle_box_new ();
  gtk_widget_show (handlebox2);
  gtk_box_pack_start (GTK_BOX (vbox6), handlebox2, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (handlebox2), 1);

  toolbar2 = gtk_toolbar_new ();
  gtk_widget_show (toolbar2);
  gtk_container_add (GTK_CONTAINER (handlebox2), toolbar2);
  gtk_container_set_border_width (GTK_CONTAINER (toolbar2), 1);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar2), GTK_TOOLBAR_BOTH);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar2));

  tmp_image = gtk_image_new_from_stock ("gtk-disconnect", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  connect_button1 = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Connect"));
  gtk_widget_show (connect_button1);
  gtk_container_add (GTK_CONTAINER (toolbar2), connect_button1);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (connect_button1), tooltips, _("Connect to Director"), NULL);

  tmp_image = gtk_image_new_from_stock ("gtk-execute", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  run_button1 = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Run"));
  gtk_widget_show (run_button1);
  gtk_container_add (GTK_CONTAINER (toolbar2), run_button1);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (run_button1), tooltips, _("Run a Job"), NULL);

  tmp_image = gtk_image_new_from_stock ("gnome-stock-text-bulleted-list", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  dir_button = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Dir Status"));
  gtk_widget_show (dir_button);
  gtk_container_add (GTK_CONTAINER (toolbar2), dir_button);

  tmp_image = gtk_image_new_from_stock ("gtk-revert-to-saved", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  restore_button = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Restore"));
  gtk_widget_show (restore_button);
  gtk_container_add (GTK_CONTAINER (toolbar2), restore_button);

  tmp_image = gtk_image_new_from_stock ("gtk-save-as", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  label_button = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Label"));
  gtk_widget_show (label_button);
  gtk_container_add (GTK_CONTAINER (toolbar2), label_button);

  tmp_image = gtk_image_new_from_stock ("gtk-find", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  msgs_button = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Msgs"));
  gtk_widget_show (msgs_button);
  gtk_container_add (GTK_CONTAINER (toolbar2), msgs_button);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (msgs_button), tooltips, _("Display Messages"), NULL);

  vbox7 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox7);
  gtk_box_pack_start (GTK_BOX (vbox6), vbox7, TRUE, TRUE, 0);

  scroll1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scroll1);
  gtk_box_pack_start (GTK_BOX (vbox7), scroll1, TRUE, TRUE, 0);
  GTK_WIDGET_UNSET_FLAGS (scroll1, GTK_CAN_FOCUS);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scroll1), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scroll1), GTK_SHADOW_IN);

  text1 = gtk_text_view_new ();
  gtk_widget_show (text1);
  gtk_container_add (GTK_CONTAINER (scroll1), text1);
  GTK_WIDGET_UNSET_FLAGS (text1, GTK_CAN_FOCUS);
  gtk_text_view_set_editable (GTK_TEXT_VIEW (text1), FALSE);
  gtk_text_view_set_wrap_mode (GTK_TEXT_VIEW (text1), GTK_WRAP_WORD);

  hbox18 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox18);
  gtk_box_pack_start (GTK_BOX (vbox7), hbox18, FALSE, TRUE, 0);

  label38 = gtk_label_new (_(" Command: "));
  gtk_widget_show (label38);
  gtk_box_pack_start (GTK_BOX (hbox18), label38, FALSE, TRUE, 0);
  gtk_label_set_justify (GTK_LABEL (label38), GTK_JUSTIFY_CENTER);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_box_pack_start (GTK_BOX (hbox18), entry1, TRUE, TRUE, 0);
  GTK_WIDGET_SET_FLAGS (entry1, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, entry1, _("Enter Commands Here"), NULL);
  gtk_entry_set_max_length (GTK_ENTRY (entry1), 150);

  hbox19 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox19);
  gtk_box_pack_start (GTK_BOX (vbox7), hbox19, FALSE, FALSE, 0);

  frame1 = gtk_frame_new (NULL);
  gtk_widget_show (frame1);
  gtk_box_pack_start (GTK_BOX (hbox19), frame1, FALSE, TRUE, 0);

  label39 = gtk_label_new (_(" Status: "));
  gtk_widget_show (label39);
  gtk_container_add (GTK_CONTAINER (frame1), label39);
  gtk_label_set_justify (GTK_LABEL (label39), GTK_JUSTIFY_CENTER);

  frame2 = gtk_frame_new (NULL);
  gtk_widget_show (frame2);
  gtk_box_pack_start (GTK_BOX (hbox19), frame2, TRUE, TRUE, 0);

  status1 = gtk_label_new (_("  "));
  gtk_widget_show (status1);
  gtk_container_add (GTK_CONTAINER (frame2), status1);
  gtk_misc_set_alignment (GTK_MISC (status1), 0, 0.5);

  g_signal_connect ((gpointer) console, "delete_event",
                    G_CALLBACK (on_console_delete_event),
                    NULL);
  g_signal_connect ((gpointer) connect_button1, "clicked",
                    G_CALLBACK (on_connect_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) run_button1, "clicked",
                    G_CALLBACK (on_run_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) dir_button, "clicked",
                    G_CALLBACK (on_dir_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) restore_button, "clicked",
                    G_CALLBACK (on_restore_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) label_button, "clicked",
                    G_CALLBACK (on_label_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) msgs_button, "clicked",
                    G_CALLBACK (on_msgs_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) entry1, "key_press_event",
                    G_CALLBACK (on_entry1_key_press_event),
                    NULL);
  g_signal_connect ((gpointer) entry1, "key_release_event",
                    G_CALLBACK (on_entry1_key_release_event),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (console, console, "console");
  GLADE_HOOKUP_OBJECT (console, vbox6, "vbox6");
  GLADE_HOOKUP_OBJECT (console, handlebox1, "handlebox1");
  GLADE_HOOKUP_OBJECT (console, menubar1, "menubar1");
  GLADE_HOOKUP_OBJECT (console, menubar1_uiinfo[0].widget, "file1");
  GLADE_HOOKUP_OBJECT (console, file1_menu_uiinfo[0].widget, "connect1");
  GLADE_HOOKUP_OBJECT (console, file1_menu_uiinfo[1].widget, "disconnect1");
  GLADE_HOOKUP_OBJECT (console, file1_menu_uiinfo[2].widget, "menuitem4");
  GLADE_HOOKUP_OBJECT (console, file1_menu_uiinfo[3].widget, "exit1");
  GLADE_HOOKUP_OBJECT (console, menubar1_uiinfo[1].widget, "edit1");
  GLADE_HOOKUP_OBJECT (console, edit1_menu_uiinfo[0].widget, "cut1");
  GLADE_HOOKUP_OBJECT (console, edit1_menu_uiinfo[1].widget, "copy1");
  GLADE_HOOKUP_OBJECT (console, edit1_menu_uiinfo[2].widget, "paste1");
  GLADE_HOOKUP_OBJECT (console, edit1_menu_uiinfo[3].widget, "clear1");
  GLADE_HOOKUP_OBJECT (console, edit1_menu_uiinfo[4].widget, "separator1");
  GLADE_HOOKUP_OBJECT (console, menubar1_uiinfo[2].widget, "item1");
  GLADE_HOOKUP_OBJECT (console, item1_menu_uiinfo[0].widget, "msgs");
  GLADE_HOOKUP_OBJECT (console, menubar1_uiinfo[3].widget, "settings1");
  GLADE_HOOKUP_OBJECT (console, settings1_menu_uiinfo[0].widget, "preferences1");
  GLADE_HOOKUP_OBJECT (console, menubar1_uiinfo[4].widget, "help1");
  GLADE_HOOKUP_OBJECT (console, help1_menu_uiinfo[0].widget, "about1");
  GLADE_HOOKUP_OBJECT (console, handlebox2, "handlebox2");
  GLADE_HOOKUP_OBJECT (console, toolbar2, "toolbar2");
  GLADE_HOOKUP_OBJECT (console, connect_button1, "connect_button1");
  GLADE_HOOKUP_OBJECT (console, run_button1, "run_button1");
  GLADE_HOOKUP_OBJECT (console, dir_button, "dir_button");
  GLADE_HOOKUP_OBJECT (console, restore_button, "restore_button");
  GLADE_HOOKUP_OBJECT (console, label_button, "label_button");
  GLADE_HOOKUP_OBJECT (console, msgs_button, "msgs_button");
  GLADE_HOOKUP_OBJECT (console, vbox7, "vbox7");
  GLADE_HOOKUP_OBJECT (console, scroll1, "scroll1");
  GLADE_HOOKUP_OBJECT (console, text1, "text1");
  GLADE_HOOKUP_OBJECT (console, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (console, label38, "label38");
  GLADE_HOOKUP_OBJECT (console, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (console, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (console, frame1, "frame1");
  GLADE_HOOKUP_OBJECT (console, label39, "label39");
  GLADE_HOOKUP_OBJECT (console, frame2, "frame2");
  GLADE_HOOKUP_OBJECT (console, status1, "status1");
  GLADE_HOOKUP_OBJECT_NO_REF (console, tooltips, "tooltips");

  gtk_widget_grab_focus (entry1);
  gtk_widget_grab_default (entry1);
  gtk_window_add_accel_group (GTK_WINDOW (console), accel_group);

  return console;
}

GtkWidget*
create_about1 (void)
{
  GtkWidget *about1;
  GtkWidget *dialog_vbox5;
  GtkWidget *vbox8;
  GtkWidget *vbox9;
  GtkWidget *about_head;
  GtkWidget *hseparator1;
  GtkWidget *copyright;
  GtkWidget *authors;
  GtkWidget *theme;
  GtkWidget *dialog_action_area5;
  GtkWidget *hbox20;
  GtkWidget *label44;
  GtkWidget *about_button;

  about1 = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (about1), _("About Bacula Console"));
  gtk_window_set_modal (GTK_WINDOW (about1), TRUE);
  gtk_window_set_type_hint (GTK_WINDOW (about1), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox5 = GTK_DIALOG (about1)->vbox;
  gtk_widget_show (dialog_vbox5);

  vbox8 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox8);
  gtk_box_pack_start (GTK_BOX (dialog_vbox5), vbox8, TRUE, TRUE, 0);

  vbox9 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox9);
  gtk_box_pack_start (GTK_BOX (vbox8), vbox9, TRUE, TRUE, 0);

  about_head = gtk_label_new (_("Bacula Console\n"));
  gtk_widget_show (about_head);
  gtk_box_pack_start (GTK_BOX (vbox9), about_head, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (about_head), GTK_JUSTIFY_CENTER);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_box_pack_start (GTK_BOX (vbox9), hseparator1, FALSE, FALSE, 0);

  copyright = gtk_label_new (_("Copyright (c) 2000 - 2004, Kern Sibbald and John Walker"));
  gtk_widget_show (copyright);
  gtk_box_pack_start (GTK_BOX (vbox9), copyright, TRUE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (copyright), 0.1, 0.5);

  authors = gtk_label_new (_("Authors: Kern Sibbald and John Walker"));
  gtk_widget_show (authors);
  gtk_box_pack_start (GTK_BOX (vbox9), authors, TRUE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (authors), 0.0400001, 0.5);

  theme = gtk_label_new (_("It comes by night and sucks the essence from your computers"));
  gtk_widget_show (theme);
  gtk_box_pack_start (GTK_BOX (vbox9), theme, TRUE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (theme), 0.15, 0.5);

  dialog_action_area5 = GTK_DIALOG (about1)->action_area;
  gtk_widget_show (dialog_action_area5);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area5), GTK_BUTTONBOX_END);

  hbox20 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (dialog_action_area5), hbox20);

  label44 = gtk_label_new ("");
  gtk_widget_show (label44);
  gtk_box_pack_start (GTK_BOX (hbox20), label44, TRUE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label44), GTK_JUSTIFY_CENTER);

  about_button = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (about_button);
  gtk_box_pack_start (GTK_BOX (hbox20), about_button, FALSE, FALSE, 0);
  gtk_widget_set_size_request (about_button, 400, 640);
  gtk_container_set_border_width (GTK_CONTAINER (about_button), 1);
  GTK_WIDGET_SET_FLAGS (about_button, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) about_button, "clicked",
                    G_CALLBACK (on_about_button_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (about1, about1, "about1");
  GLADE_HOOKUP_OBJECT_NO_REF (about1, dialog_vbox5, "dialog_vbox5");
  GLADE_HOOKUP_OBJECT (about1, vbox8, "vbox8");
  GLADE_HOOKUP_OBJECT (about1, vbox9, "vbox9");
  GLADE_HOOKUP_OBJECT (about1, about_head, "about_head");
  GLADE_HOOKUP_OBJECT (about1, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (about1, copyright, "copyright");
  GLADE_HOOKUP_OBJECT (about1, authors, "authors");
  GLADE_HOOKUP_OBJECT (about1, theme, "theme");
  GLADE_HOOKUP_OBJECT_NO_REF (about1, dialog_action_area5, "dialog_action_area5");
  GLADE_HOOKUP_OBJECT (about1, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (about1, label44, "label44");
  GLADE_HOOKUP_OBJECT (about1, about_button, "about_button");

  return about1;
}

GtkWidget*
create_SelectDirectorDialog (void)
{
  GtkWidget *SelectDirectorDialog;
  GtkWidget *dialog_vbox6;
  GtkWidget *vbox10;
  GtkWidget *label48;
  GtkWidget *label47;
  GtkWidget *combo1;
  GList *combo1_items = NULL;
  GtkWidget *dirselect;
  GtkWidget *dialog_action_area2;
  GtkWidget *hbox21;
  GtkWidget *button11;
  GtkWidget *label46;
  GtkWidget *button13;

  SelectDirectorDialog = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (SelectDirectorDialog), _("Select Director"));
  gtk_window_set_modal (GTK_WINDOW (SelectDirectorDialog), TRUE);
  gtk_window_set_type_hint (GTK_WINDOW (SelectDirectorDialog), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox6 = GTK_DIALOG (SelectDirectorDialog)->vbox;
  gtk_widget_show (dialog_vbox6);

  vbox10 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox10);
  gtk_box_pack_start (GTK_BOX (dialog_vbox6), vbox10, TRUE, TRUE, 0);

  label48 = gtk_label_new ("");
  gtk_widget_show (label48);
  gtk_box_pack_start (GTK_BOX (vbox10), label48, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label48), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (label48), 0.48, 0.46);

  label47 = gtk_label_new (_("Select Director"));
  gtk_widget_show (label47);
  gtk_box_pack_start (GTK_BOX (vbox10), label47, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label47), GTK_JUSTIFY_CENTER);

  combo1 = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo1)->popwin),
                     "GladeParentKey", combo1);
  gtk_widget_show (combo1);
  gtk_box_pack_start (GTK_BOX (vbox10), combo1, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (combo1), 6);
  combo1_items = g_list_append (combo1_items, (gpointer) "");
  gtk_combo_set_popdown_strings (GTK_COMBO (combo1), combo1_items);
  g_list_free (combo1_items);

  dirselect = GTK_COMBO (combo1)->entry;
  gtk_widget_show (dirselect);

  dialog_action_area2 = GTK_DIALOG (SelectDirectorDialog)->action_area;
  gtk_widget_show (dialog_action_area2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area2), GTK_BUTTONBOX_END);

  hbox21 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox21);
  gtk_container_add (GTK_CONTAINER (dialog_action_area2), hbox21);

  button11 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (button11);
  gtk_box_pack_start (GTK_BOX (hbox21), button11, FALSE, FALSE, 0);

  label46 = gtk_label_new (_("         "));
  gtk_widget_show (label46);
  gtk_box_pack_start (GTK_BOX (hbox21), label46, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label46), GTK_JUSTIFY_CENTER);
  gtk_misc_set_padding (GTK_MISC (label46), 2, 0);

  button13 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (button13);
  gtk_box_pack_start (GTK_BOX (hbox21), button13, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button11, "clicked",
                    G_CALLBACK (on_select_director_OK_clicked),
                    NULL);
  g_signal_connect ((gpointer) button13, "clicked",
                    G_CALLBACK (on_select_director_cancel_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (SelectDirectorDialog, SelectDirectorDialog, "SelectDirectorDialog");
  GLADE_HOOKUP_OBJECT_NO_REF (SelectDirectorDialog, dialog_vbox6, "dialog_vbox6");
  GLADE_HOOKUP_OBJECT (SelectDirectorDialog, vbox10, "vbox10");
  GLADE_HOOKUP_OBJECT (SelectDirectorDialog, label48, "label48");
  GLADE_HOOKUP_OBJECT (SelectDirectorDialog, label47, "label47");
  GLADE_HOOKUP_OBJECT (SelectDirectorDialog, combo1, "combo1");
  GLADE_HOOKUP_OBJECT (SelectDirectorDialog, dirselect, "dirselect");
  GLADE_HOOKUP_OBJECT_NO_REF (SelectDirectorDialog, dialog_action_area2, "dialog_action_area2");
  GLADE_HOOKUP_OBJECT (SelectDirectorDialog, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (SelectDirectorDialog, button11, "button11");
  GLADE_HOOKUP_OBJECT (SelectDirectorDialog, label46, "label46");
  GLADE_HOOKUP_OBJECT (SelectDirectorDialog, button13, "button13");

  return SelectDirectorDialog;
}

GtkWidget*
create_RunDialog (void)
{
  GtkWidget *RunDialog;
  GtkWidget *dialog_vbox7;
  GtkWidget *vbox11;
  GtkWidget *vbox12;
  GtkWidget *label62;
  GtkWidget *alignment1;
  GtkWidget *hbox28;
  GtkWidget *hbox29;
  GtkWidget *label63;
  GtkWidget *combo_job;
  GList *combo_job_items = NULL;
  GtkWidget *entry_job;
  GtkWidget *label64;
  GtkWidget *combo_type;
  GList *combo_type_items = NULL;
  GtkWidget *entry_type;
  GtkWidget *label114;
  GtkWidget *hbox30;
  GtkWidget *label66;
  GtkWidget *combo_client;
  GList *combo_client_items = NULL;
  GtkWidget *entry_client;
  GtkWidget *label67;
  GtkWidget *hbox31;
  GtkWidget *label68;
  GtkWidget *combo_fileset;
  GList *combo_fileset_items = NULL;
  GtkWidget *entry_fileset;
  GtkWidget *label156;
  GtkWidget *label155;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkWidget *hbox32;
  GtkWidget *label70;
  GtkWidget *combo_level;
  GList *combo_level_items = NULL;
  GtkWidget *entry_level;
  GtkWidget *label71;
  GtkWidget *hbox33;
  GtkWidget *label72;
  GtkWidget *combo_pool;
  GList *combo_pool_items = NULL;
  GtkWidget *entry_pool;
  GtkWidget *label73;
  GtkWidget *hbox39;
  GtkWidget *label96;
  GtkWidget *combo_storage;
  GList *combo_storage_items = NULL;
  GtkWidget *entry_storage;
  GtkWidget *label97;
  GtkWidget *hbox40;
  GtkWidget *label98;
  GtkWidget *combo_messages;
  GList *combo_messages_items = NULL;
  GtkWidget *entry_messages;
  GtkWidget *label99;
  GtkWidget *hbox34;
  GtkWidget *label77;
  GtkWidget *entry_where;
  GtkWidget *label78;
  GtkWidget *hbox41;
  GtkWidget *label100;
  GtkWidget *entry_when;
  GtkWidget *label101;
  GtkWidget *hbox60;
  GtkWidget *label153;
  GtkWidget *entry28;
  GtkWidget *label154;
  GtkWidget *label84;
  GtkWidget *dialog_action_area6;
  GtkWidget *hbuttonbox1;
  GtkWidget *run_ok;
  GtkWidget *run_cancel;

  RunDialog = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (RunDialog), _("Run a Job"));
  gtk_window_set_type_hint (GTK_WINDOW (RunDialog), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox7 = GTK_DIALOG (RunDialog)->vbox;
  gtk_widget_show (dialog_vbox7);

  vbox11 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox11);
  gtk_box_pack_start (GTK_BOX (dialog_vbox7), vbox11, TRUE, TRUE, 0);

  vbox12 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox12);
  gtk_box_pack_start (GTK_BOX (vbox11), vbox12, TRUE, TRUE, 0);

  label62 = gtk_label_new (_("Run a Job"));
  gtk_widget_show (label62);
  gtk_box_pack_start (GTK_BOX (vbox12), label62, FALSE, FALSE, 2);
  gtk_label_set_justify (GTK_LABEL (label62), GTK_JUSTIFY_CENTER);
  gtk_misc_set_padding (GTK_MISC (label62), 0, 9);

  alignment1 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment1);
  gtk_box_pack_start (GTK_BOX (vbox12), alignment1, FALSE, FALSE, 2);

  hbox28 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox28);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox28);
  gtk_container_set_border_width (GTK_CONTAINER (hbox28), 1);

  hbox29 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox29);
  gtk_box_pack_start (GTK_BOX (hbox28), hbox29, TRUE, TRUE, 0);

  label63 = gtk_label_new (_("Job:"));
  gtk_widget_show (label63);
  gtk_box_pack_start (GTK_BOX (hbox29), label63, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label63, 85, 16);
  gtk_label_set_justify (GTK_LABEL (label63), GTK_JUSTIFY_RIGHT);

  combo_job = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo_job)->popwin),
                     "GladeParentKey", combo_job);
  gtk_widget_show (combo_job);
  gtk_box_pack_start (GTK_BOX (hbox29), combo_job, TRUE, TRUE, 1);
  gtk_widget_set_size_request (combo_job, 198, -1);
  gtk_combo_set_value_in_list (GTK_COMBO (combo_job), TRUE, FALSE);
  combo_job_items = g_list_append (combo_job_items, (gpointer) "");
  gtk_combo_set_popdown_strings (GTK_COMBO (combo_job), combo_job_items);
  g_list_free (combo_job_items);

  entry_job = GTK_COMBO (combo_job)->entry;
  gtk_widget_show (entry_job);
  gtk_editable_set_editable (GTK_EDITABLE (entry_job), FALSE);

  label64 = gtk_label_new (_("   Type:"));
  gtk_widget_show (label64);
  gtk_box_pack_start (GTK_BOX (hbox29), label64, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label64), GTK_JUSTIFY_CENTER);

  combo_type = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo_type)->popwin),
                     "GladeParentKey", combo_type);
  gtk_widget_show (combo_type);
  gtk_box_pack_start (GTK_BOX (hbox29), combo_type, FALSE, FALSE, 0);
  gtk_widget_set_size_request (combo_type, 141, 24);
  gtk_combo_set_value_in_list (GTK_COMBO (combo_type), TRUE, FALSE);
  combo_type_items = g_list_append (combo_type_items, (gpointer) "");
  gtk_combo_set_popdown_strings (GTK_COMBO (combo_type), combo_type_items);
  g_list_free (combo_type_items);

  entry_type = GTK_COMBO (combo_type)->entry;
  gtk_widget_show (entry_type);
  gtk_editable_set_editable (GTK_EDITABLE (entry_type), FALSE);

  label114 = gtk_label_new (_(" "));
  gtk_widget_show (label114);
  gtk_box_pack_start (GTK_BOX (hbox28), label114, FALSE, FALSE, 30);

  hbox30 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox30);
  gtk_box_pack_start (GTK_BOX (vbox12), hbox30, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox30), 1);

  label66 = gtk_label_new (_("Client:"));
  gtk_widget_show (label66);
  gtk_box_pack_start (GTK_BOX (hbox30), label66, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label66, 85, 16);
  gtk_label_set_justify (GTK_LABEL (label66), GTK_JUSTIFY_RIGHT);

  combo_client = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo_client)->popwin),
                     "GladeParentKey", combo_client);
  gtk_widget_show (combo_client);
  gtk_box_pack_start (GTK_BOX (hbox30), combo_client, TRUE, TRUE, 1);
  gtk_combo_set_value_in_list (GTK_COMBO (combo_client), TRUE, FALSE);
  combo_client_items = g_list_append (combo_client_items, (gpointer) "");
  gtk_combo_set_popdown_strings (GTK_COMBO (combo_client), combo_client_items);
  g_list_free (combo_client_items);

  entry_client = GTK_COMBO (combo_client)->entry;
  gtk_widget_show (entry_client);
  gtk_editable_set_editable (GTK_EDITABLE (entry_client), FALSE);

  label67 = gtk_label_new (_(" "));
  gtk_widget_show (label67);
  gtk_box_pack_start (GTK_BOX (hbox30), label67, FALSE, FALSE, 123);
  gtk_label_set_justify (GTK_LABEL (label67), GTK_JUSTIFY_CENTER);

  hbox31 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox31);
  gtk_box_pack_start (GTK_BOX (vbox12), hbox31, TRUE, TRUE, 2);
  gtk_container_set_border_width (GTK_CONTAINER (hbox31), 1);

  label68 = gtk_label_new (_("FileSet: "));
  gtk_widget_show (label68);
  gtk_box_pack_start (GTK_BOX (hbox31), label68, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label68, 85, 16);
  gtk_label_set_justify (GTK_LABEL (label68), GTK_JUSTIFY_RIGHT);

  combo_fileset = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo_fileset)->popwin),
                     "GladeParentKey", combo_fileset);
  gtk_widget_show (combo_fileset);
  gtk_box_pack_start (GTK_BOX (hbox31), combo_fileset, TRUE, TRUE, 0);
  gtk_combo_set_value_in_list (GTK_COMBO (combo_fileset), TRUE, FALSE);
  combo_fileset_items = g_list_append (combo_fileset_items, (gpointer) "");
  gtk_combo_set_popdown_strings (GTK_COMBO (combo_fileset), combo_fileset_items);
  g_list_free (combo_fileset_items);

  entry_fileset = GTK_COMBO (combo_fileset)->entry;
  gtk_widget_show (entry_fileset);
  gtk_editable_set_editable (GTK_EDITABLE (entry_fileset), FALSE);

  label156 = gtk_label_new ("");
  gtk_widget_show (label156);
  gtk_box_pack_start (GTK_BOX (hbox31), label156, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label156, 13, 16);

  label155 = gtk_label_new (_("Priority:"));
  gtk_widget_show (label155);
  gtk_box_pack_start (GTK_BOX (hbox31), label155, TRUE, TRUE, 0);
  gtk_widget_set_size_request (label155, 103, -1);

  spinbutton1_adj = gtk_adjustment_new (10, 0, 100, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_box_pack_start (GTK_BOX (hbox31), spinbutton1, TRUE, TRUE, 4);
  gtk_widget_set_size_request (spinbutton1, 85, 24);

  hbox32 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox32);
  gtk_box_pack_start (GTK_BOX (vbox12), hbox32, TRUE, TRUE, 2);
  gtk_container_set_border_width (GTK_CONTAINER (hbox32), 1);

  label70 = gtk_label_new (_("Level:"));
  gtk_widget_show (label70);
  gtk_box_pack_start (GTK_BOX (hbox32), label70, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label70, 85, 16);
  gtk_label_set_justify (GTK_LABEL (label70), GTK_JUSTIFY_RIGHT);

  combo_level = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo_level)->popwin),
                     "GladeParentKey", combo_level);
  gtk_widget_show (combo_level);
  gtk_box_pack_start (GTK_BOX (hbox32), combo_level, TRUE, TRUE, 0);
  gtk_combo_set_value_in_list (GTK_COMBO (combo_level), TRUE, FALSE);
  combo_level_items = g_list_append (combo_level_items, (gpointer) "");
  combo_level_items = g_list_append (combo_level_items, (gpointer) "");
  gtk_combo_set_popdown_strings (GTK_COMBO (combo_level), combo_level_items);
  g_list_free (combo_level_items);

  entry_level = GTK_COMBO (combo_level)->entry;
  gtk_widget_show (entry_level);
  gtk_editable_set_editable (GTK_EDITABLE (entry_level), FALSE);

  label71 = gtk_label_new (_("             "));
  gtk_widget_show (label71);
  gtk_box_pack_start (GTK_BOX (hbox32), label71, FALSE, FALSE, 100);
  gtk_label_set_justify (GTK_LABEL (label71), GTK_JUSTIFY_CENTER);

  hbox33 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox33);
  gtk_box_pack_start (GTK_BOX (vbox12), hbox33, TRUE, TRUE, 2);
  gtk_container_set_border_width (GTK_CONTAINER (hbox33), 1);

  label72 = gtk_label_new (_("Pool:"));
  gtk_widget_show (label72);
  gtk_box_pack_start (GTK_BOX (hbox33), label72, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label72, 85, 16);
  gtk_label_set_justify (GTK_LABEL (label72), GTK_JUSTIFY_CENTER);

  combo_pool = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo_pool)->popwin),
                     "GladeParentKey", combo_pool);
  gtk_widget_show (combo_pool);
  gtk_box_pack_start (GTK_BOX (hbox33), combo_pool, TRUE, TRUE, 0);
  gtk_combo_set_value_in_list (GTK_COMBO (combo_pool), TRUE, FALSE);
  combo_pool_items = g_list_append (combo_pool_items, (gpointer) "");
  combo_pool_items = g_list_append (combo_pool_items, (gpointer) "");
  gtk_combo_set_popdown_strings (GTK_COMBO (combo_pool), combo_pool_items);
  g_list_free (combo_pool_items);

  entry_pool = GTK_COMBO (combo_pool)->entry;
  gtk_widget_show (entry_pool);
  gtk_editable_set_editable (GTK_EDITABLE (entry_pool), FALSE);

  label73 = gtk_label_new (_("   "));
  gtk_widget_show (label73);
  gtk_box_pack_start (GTK_BOX (hbox33), label73, FALSE, FALSE, 120);
  gtk_label_set_justify (GTK_LABEL (label73), GTK_JUSTIFY_CENTER);

  hbox39 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox39);
  gtk_box_pack_start (GTK_BOX (vbox12), hbox39, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox39), 1);

  label96 = gtk_label_new (_("Storage:"));
  gtk_widget_show (label96);
  gtk_box_pack_start (GTK_BOX (hbox39), label96, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label96, 85, 16);
  gtk_label_set_justify (GTK_LABEL (label96), GTK_JUSTIFY_CENTER);

  combo_storage = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo_storage)->popwin),
                     "GladeParentKey", combo_storage);
  gtk_widget_show (combo_storage);
  gtk_box_pack_start (GTK_BOX (hbox39), combo_storage, TRUE, TRUE, 0);
  gtk_combo_set_value_in_list (GTK_COMBO (combo_storage), TRUE, FALSE);
  combo_storage_items = g_list_append (combo_storage_items, (gpointer) "");
  combo_storage_items = g_list_append (combo_storage_items, (gpointer) "");
  gtk_combo_set_popdown_strings (GTK_COMBO (combo_storage), combo_storage_items);
  g_list_free (combo_storage_items);

  entry_storage = GTK_COMBO (combo_storage)->entry;
  gtk_widget_show (entry_storage);
  gtk_editable_set_editable (GTK_EDITABLE (entry_storage), FALSE);

  label97 = gtk_label_new (_("   "));
  gtk_widget_show (label97);
  gtk_box_pack_start (GTK_BOX (hbox39), label97, FALSE, FALSE, 120);
  gtk_label_set_justify (GTK_LABEL (label97), GTK_JUSTIFY_CENTER);

  hbox40 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox40);
  gtk_box_pack_start (GTK_BOX (vbox12), hbox40, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox40), 1);

  label98 = gtk_label_new (_("Messages:"));
  gtk_widget_show (label98);
  gtk_box_pack_start (GTK_BOX (hbox40), label98, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label98, 85, 16);
  gtk_label_set_justify (GTK_LABEL (label98), GTK_JUSTIFY_CENTER);

  combo_messages = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo_messages)->popwin),
                     "GladeParentKey", combo_messages);
  gtk_widget_show (combo_messages);
  gtk_box_pack_start (GTK_BOX (hbox40), combo_messages, TRUE, TRUE, 0);
  gtk_combo_set_value_in_list (GTK_COMBO (combo_messages), TRUE, FALSE);
  combo_messages_items = g_list_append (combo_messages_items, (gpointer) "");
  gtk_combo_set_popdown_strings (GTK_COMBO (combo_messages), combo_messages_items);
  g_list_free (combo_messages_items);

  entry_messages = GTK_COMBO (combo_messages)->entry;
  gtk_widget_show (entry_messages);
  gtk_editable_set_editable (GTK_EDITABLE (entry_messages), FALSE);

  label99 = gtk_label_new (_("   "));
  gtk_widget_show (label99);
  gtk_box_pack_start (GTK_BOX (hbox40), label99, FALSE, FALSE, 120);
  gtk_label_set_justify (GTK_LABEL (label99), GTK_JUSTIFY_CENTER);

  hbox34 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox34);
  gtk_box_pack_start (GTK_BOX (vbox12), hbox34, TRUE, TRUE, 2);
  gtk_container_set_border_width (GTK_CONTAINER (hbox34), 1);

  label77 = gtk_label_new (_("Where: "));
  gtk_widget_show (label77);
  gtk_box_pack_start (GTK_BOX (hbox34), label77, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label77, 85, 16);
  gtk_label_set_justify (GTK_LABEL (label77), GTK_JUSTIFY_CENTER);

  entry_where = gtk_entry_new ();
  gtk_widget_show (entry_where);
  gtk_box_pack_start (GTK_BOX (hbox34), entry_where, TRUE, TRUE, 0);

  label78 = gtk_label_new (_("   "));
  gtk_widget_show (label78);
  gtk_box_pack_start (GTK_BOX (hbox34), label78, FALSE, FALSE, 120);
  gtk_label_set_justify (GTK_LABEL (label78), GTK_JUSTIFY_CENTER);

  hbox41 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox41);
  gtk_box_pack_start (GTK_BOX (vbox11), hbox41, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox41), 1);

  label100 = gtk_label_new (_("When:"));
  gtk_widget_show (label100);
  gtk_box_pack_start (GTK_BOX (hbox41), label100, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label100, 85, 16);
  gtk_label_set_justify (GTK_LABEL (label100), GTK_JUSTIFY_CENTER);

  entry_when = gtk_entry_new ();
  gtk_widget_show (entry_when);
  gtk_box_pack_start (GTK_BOX (hbox41), entry_when, TRUE, TRUE, 0);

  label101 = gtk_label_new (_("   "));
  gtk_widget_show (label101);
  gtk_box_pack_start (GTK_BOX (hbox41), label101, FALSE, FALSE, 120);
  gtk_label_set_justify (GTK_LABEL (label101), GTK_JUSTIFY_CENTER);

  hbox60 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox60);
  gtk_box_pack_start (GTK_BOX (vbox11), hbox60, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox60), 1);

  label153 = gtk_label_new (_("Bootstrap:"));
  gtk_widget_show (label153);
  gtk_box_pack_start (GTK_BOX (hbox60), label153, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label153, 85, 16);
  gtk_label_set_justify (GTK_LABEL (label153), GTK_JUSTIFY_CENTER);

  entry28 = gtk_entry_new ();
  gtk_widget_show (entry28);
  gtk_box_pack_start (GTK_BOX (hbox60), entry28, TRUE, TRUE, 0);

  label154 = gtk_label_new (_("   "));
  gtk_widget_show (label154);
  gtk_box_pack_start (GTK_BOX (hbox60), label154, FALSE, FALSE, 36);
  gtk_label_set_justify (GTK_LABEL (label154), GTK_JUSTIFY_CENTER);

  label84 = gtk_label_new (_("   "));
  gtk_widget_show (label84);
  gtk_box_pack_start (GTK_BOX (vbox11), label84, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label84, 12, 19);
  gtk_label_set_justify (GTK_LABEL (label84), GTK_JUSTIFY_CENTER);

  dialog_action_area6 = GTK_DIALOG (RunDialog)->action_area;
  gtk_widget_show (dialog_action_area6);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area6), GTK_BUTTONBOX_END);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox1);
  gtk_container_add (GTK_CONTAINER (dialog_action_area6), hbuttonbox1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox1), GTK_BUTTONBOX_END);
  gtk_box_set_spacing (GTK_BOX (hbuttonbox1), 8);

  run_ok = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (run_ok);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), run_ok);
  GTK_WIDGET_SET_FLAGS (run_ok, GTK_CAN_DEFAULT);

  run_cancel = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (run_cancel);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), run_cancel);
  GTK_WIDGET_SET_FLAGS (run_cancel, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) entry_job, "changed",
                    G_CALLBACK (on_entry_job_changed),
                    NULL);
  g_signal_connect ((gpointer) run_ok, "clicked",
                    G_CALLBACK (on_run_ok_clicked),
                    NULL);
  g_signal_connect ((gpointer) run_cancel, "clicked",
                    G_CALLBACK (on_run_cancel_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (RunDialog, RunDialog, "RunDialog");
  GLADE_HOOKUP_OBJECT_NO_REF (RunDialog, dialog_vbox7, "dialog_vbox7");
  GLADE_HOOKUP_OBJECT (RunDialog, vbox11, "vbox11");
  GLADE_HOOKUP_OBJECT (RunDialog, vbox12, "vbox12");
  GLADE_HOOKUP_OBJECT (RunDialog, label62, "label62");
  GLADE_HOOKUP_OBJECT (RunDialog, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (RunDialog, hbox28, "hbox28");
  GLADE_HOOKUP_OBJECT (RunDialog, hbox29, "hbox29");
  GLADE_HOOKUP_OBJECT (RunDialog, label63, "label63");
  GLADE_HOOKUP_OBJECT (RunDialog, combo_job, "combo_job");
  GLADE_HOOKUP_OBJECT (RunDialog, entry_job, "entry_job");
  GLADE_HOOKUP_OBJECT (RunDialog, label64, "label64");
  GLADE_HOOKUP_OBJECT (RunDialog, combo_type, "combo_type");
  GLADE_HOOKUP_OBJECT (RunDialog, entry_type, "entry_type");
  GLADE_HOOKUP_OBJECT (RunDialog, label114, "label114");
  GLADE_HOOKUP_OBJECT (RunDialog, hbox30, "hbox30");
  GLADE_HOOKUP_OBJECT (RunDialog, label66, "label66");
  GLADE_HOOKUP_OBJECT (RunDialog, combo_client, "combo_client");
  GLADE_HOOKUP_OBJECT (RunDialog, entry_client, "entry_client");
  GLADE_HOOKUP_OBJECT (RunDialog, label67, "label67");
  GLADE_HOOKUP_OBJECT (RunDialog, hbox31, "hbox31");
  GLADE_HOOKUP_OBJECT (RunDialog, label68, "label68");
  GLADE_HOOKUP_OBJECT (RunDialog, combo_fileset, "combo_fileset");
  GLADE_HOOKUP_OBJECT (RunDialog, entry_fileset, "entry_fileset");
  GLADE_HOOKUP_OBJECT (RunDialog, label156, "label156");
  GLADE_HOOKUP_OBJECT (RunDialog, label155, "label155");
  GLADE_HOOKUP_OBJECT (RunDialog, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (RunDialog, hbox32, "hbox32");
  GLADE_HOOKUP_OBJECT (RunDialog, label70, "label70");
  GLADE_HOOKUP_OBJECT (RunDialog, combo_level, "combo_level");
  GLADE_HOOKUP_OBJECT (RunDialog, entry_level, "entry_level");
  GLADE_HOOKUP_OBJECT (RunDialog, label71, "label71");
  GLADE_HOOKUP_OBJECT (RunDialog, hbox33, "hbox33");
  GLADE_HOOKUP_OBJECT (RunDialog, label72, "label72");
  GLADE_HOOKUP_OBJECT (RunDialog, combo_pool, "combo_pool");
  GLADE_HOOKUP_OBJECT (RunDialog, entry_pool, "entry_pool");
  GLADE_HOOKUP_OBJECT (RunDialog, label73, "label73");
  GLADE_HOOKUP_OBJECT (RunDialog, hbox39, "hbox39");
  GLADE_HOOKUP_OBJECT (RunDialog, label96, "label96");
  GLADE_HOOKUP_OBJECT (RunDialog, combo_storage, "combo_storage");
  GLADE_HOOKUP_OBJECT (RunDialog, entry_storage, "entry_storage");
  GLADE_HOOKUP_OBJECT (RunDialog, label97, "label97");
  GLADE_HOOKUP_OBJECT (RunDialog, hbox40, "hbox40");
  GLADE_HOOKUP_OBJECT (RunDialog, label98, "label98");
  GLADE_HOOKUP_OBJECT (RunDialog, combo_messages, "combo_messages");
  GLADE_HOOKUP_OBJECT (RunDialog, entry_messages, "entry_messages");
  GLADE_HOOKUP_OBJECT (RunDialog, label99, "label99");
  GLADE_HOOKUP_OBJECT (RunDialog, hbox34, "hbox34");
  GLADE_HOOKUP_OBJECT (RunDialog, label77, "label77");
  GLADE_HOOKUP_OBJECT (RunDialog, entry_where, "entry_where");
  GLADE_HOOKUP_OBJECT (RunDialog, label78, "label78");
  GLADE_HOOKUP_OBJECT (RunDialog, hbox41, "hbox41");
  GLADE_HOOKUP_OBJECT (RunDialog, label100, "label100");
  GLADE_HOOKUP_OBJECT (RunDialog, entry_when, "entry_when");
  GLADE_HOOKUP_OBJECT (RunDialog, label101, "label101");
  GLADE_HOOKUP_OBJECT (RunDialog, hbox60, "hbox60");
  GLADE_HOOKUP_OBJECT (RunDialog, label153, "label153");
  GLADE_HOOKUP_OBJECT (RunDialog, entry28, "entry28");
  GLADE_HOOKUP_OBJECT (RunDialog, label154, "label154");
  GLADE_HOOKUP_OBJECT (RunDialog, label84, "label84");
  GLADE_HOOKUP_OBJECT_NO_REF (RunDialog, dialog_action_area6, "dialog_action_area6");
  GLADE_HOOKUP_OBJECT (RunDialog, hbuttonbox1, "hbuttonbox1");
  GLADE_HOOKUP_OBJECT (RunDialog, run_ok, "run_ok");
  GLADE_HOOKUP_OBJECT (RunDialog, run_cancel, "run_cancel");

  return RunDialog;
}

static GnomeUIInfo file2_menu_uiinfo[] =
{
  GNOMEUIINFO_MENU_NEW_ITEM (N_("_New"), NULL, on_new1_activate, NULL),
  GNOMEUIINFO_MENU_OPEN_ITEM (on_open1_activate, NULL),
  GNOMEUIINFO_MENU_SAVE_ITEM (on_save1_activate, NULL),
  GNOMEUIINFO_MENU_SAVE_AS_ITEM (on_save_as1_activate, NULL),
  GNOMEUIINFO_SEPARATOR,
  GNOMEUIINFO_MENU_EXIT_ITEM (on_quit1_activate, NULL),
  GNOMEUIINFO_END
};

static GnomeUIInfo edit2_menu_uiinfo[] =
{
  GNOMEUIINFO_MENU_CUT_ITEM (on_cut2_activate, NULL),
  GNOMEUIINFO_MENU_COPY_ITEM (on_copy2_activate, NULL),
  GNOMEUIINFO_MENU_PASTE_ITEM (on_paste2_activate, NULL),
  GNOMEUIINFO_MENU_CLEAR_ITEM (on_clear2_activate, NULL),
  GNOMEUIINFO_SEPARATOR,
  GNOMEUIINFO_MENU_PROPERTIES_ITEM (on_properties1_activate, NULL),
  GNOMEUIINFO_SEPARATOR,
  GNOMEUIINFO_MENU_PREFERENCES_ITEM (on_preferences2_activate, NULL),
  GNOMEUIINFO_END
};

static GnomeUIInfo view1_menu_uiinfo[] =
{
  GNOMEUIINFO_END
};

static GnomeUIInfo help2_menu_uiinfo[] =
{
  GNOMEUIINFO_MENU_ABOUT_ITEM (on_about2_activate, NULL),
  GNOMEUIINFO_END
};

static GnomeUIInfo menubar2_uiinfo[] =
{
  GNOMEUIINFO_MENU_FILE_TREE (file2_menu_uiinfo),
  GNOMEUIINFO_MENU_EDIT_TREE (edit2_menu_uiinfo),
  GNOMEUIINFO_MENU_VIEW_TREE (view1_menu_uiinfo),
  GNOMEUIINFO_MENU_HELP_TREE (help2_menu_uiinfo),
  GNOMEUIINFO_END
};

GtkWidget*
create_restore_file_selection (void)
{
  GtkWidget *restore_file_selection;
  GtkWidget *vbox13;
  GtkWidget *handlebox4;
  GtkWidget *menubar2;
  GtkWidget *handlebox3;
  GtkWidget *toolbar3;
  GtkIconSize tmp_toolbar_icon_size;
  GtkWidget *restore_up_button;
  GtkWidget *restore_add_button;
  GtkWidget *restore_remove_button;
  GtkWidget *hbox38;
  GtkWidget *label88;
  GtkWidget *restore_dir;
  GtkWidget *hpaned1;
  GtkWidget *tree;
  GtkWidget *scrolled;
  GtkWidget *hbox44;
  GtkWidget *FilesSelected;
  GtkWidget *restore_select_ok;
  GtkWidget *label152;
  GtkWidget *restore_select_cancel;
  GtkWidget *label1001;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  restore_file_selection = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (restore_file_selection, 640, 480);
  gtk_window_set_title (GTK_WINDOW (restore_file_selection), _("Restore File Selection"));
  gtk_window_set_modal (GTK_WINDOW (restore_file_selection), TRUE);
  gtk_window_set_default_size (GTK_WINDOW (restore_file_selection), 700, 450);

  vbox13 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox13);
  gtk_container_add (GTK_CONTAINER (restore_file_selection), vbox13);

  handlebox4 = gtk_handle_box_new ();
  gtk_widget_show (handlebox4);
  gtk_box_pack_start (GTK_BOX (vbox13), handlebox4, FALSE, FALSE, 0);

  menubar2 = gtk_menu_bar_new ();
  gtk_widget_show (menubar2);
  gtk_container_add (GTK_CONTAINER (handlebox4), menubar2);
  gnome_app_fill_menu (GTK_MENU_SHELL (menubar2), menubar2_uiinfo,
                       accel_group, FALSE, 0);

  handlebox3 = gtk_handle_box_new ();
  gtk_widget_show (handlebox3);
  gtk_box_pack_start (GTK_BOX (vbox13), handlebox3, FALSE, FALSE, 0);

  toolbar3 = gtk_toolbar_new ();
  gtk_widget_show (toolbar3);
  gtk_container_add (GTK_CONTAINER (handlebox3), toolbar3);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar3), GTK_TOOLBAR_BOTH);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar3));

  restore_up_button = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-go-up");
  gtk_widget_show (restore_up_button);
  gtk_container_add (GTK_CONTAINER (toolbar3), restore_up_button);

  restore_add_button = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-add");
  gtk_widget_show (restore_add_button);
  gtk_container_add (GTK_CONTAINER (toolbar3), restore_add_button);

  restore_remove_button = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-remove");
  gtk_widget_show (restore_remove_button);
  gtk_container_add (GTK_CONTAINER (toolbar3), restore_remove_button);

  hbox38 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox38);
  gtk_box_pack_start (GTK_BOX (vbox13), hbox38, FALSE, TRUE, 0);

  label88 = gtk_label_new (_("Current dir:"));
  gtk_widget_show (label88);
  gtk_box_pack_start (GTK_BOX (hbox38), label88, FALSE, TRUE, 0);
  gtk_label_set_justify (GTK_LABEL (label88), GTK_JUSTIFY_CENTER);

  restore_dir = gtk_entry_new ();
  gtk_widget_show (restore_dir);
  gtk_box_pack_start (GTK_BOX (hbox38), restore_dir, TRUE, TRUE, 0);

  hpaned1 = gtk_hpaned_new ();
  gtk_widget_show (hpaned1);
  gtk_box_pack_start (GTK_BOX (vbox13), hpaned1, TRUE, TRUE, 0);

  tree = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (tree);
  gtk_paned_pack1 (GTK_PANED (hpaned1), tree, FALSE, TRUE);
  gtk_widget_set_size_request (tree, 164, 78);

  scrolled = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolled);
  gtk_paned_pack2 (GTK_PANED (hpaned1), scrolled, TRUE, TRUE);

  hbox44 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox44);
  gtk_box_pack_start (GTK_BOX (vbox13), hbox44, FALSE, TRUE, 5);
  gtk_widget_set_size_request (hbox44, 301, 30);

  FilesSelected = gtk_label_new (_("Files Selected: "));
  gtk_widget_show (FilesSelected);
  gtk_box_pack_start (GTK_BOX (hbox44), FilesSelected, TRUE, TRUE, 0);
  gtk_misc_set_alignment (GTK_MISC (FilesSelected), 0.02, 0.5);

  restore_select_ok = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (restore_select_ok);
  gtk_box_pack_start (GTK_BOX (hbox44), restore_select_ok, FALSE, TRUE, 0);
  gtk_widget_set_size_request (restore_select_ok, 72, 30);

  label152 = gtk_label_new ("");
  gtk_widget_show (label152);
  gtk_box_pack_start (GTK_BOX (hbox44), label152, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label152, 34, 16);

  restore_select_cancel = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (restore_select_cancel);
  gtk_box_pack_start (GTK_BOX (hbox44), restore_select_cancel, FALSE, TRUE, 0);

  label1001 = gtk_label_new (_(" "));
  gtk_widget_show (label1001);
  gtk_box_pack_start (GTK_BOX (hbox44), label1001, FALSE, FALSE, 8);

  g_signal_connect ((gpointer) restore_file_selection, "delete_event",
                    G_CALLBACK (on_restore_files_delete_event),
                    NULL);
  g_signal_connect ((gpointer) restore_up_button, "clicked",
                    G_CALLBACK (on_restore_up_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) restore_add_button, "clicked",
                    G_CALLBACK (on_restore_add_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) restore_remove_button, "clicked",
                    G_CALLBACK (on_restore_remove_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) restore_select_ok, "clicked",
                    G_CALLBACK (on_restore_select_ok_clicked),
                    NULL);
  g_signal_connect ((gpointer) restore_select_cancel, "clicked",
                    G_CALLBACK (on_restore_select_cancel_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (restore_file_selection, restore_file_selection, "restore_file_selection");
  GLADE_HOOKUP_OBJECT (restore_file_selection, vbox13, "vbox13");
  GLADE_HOOKUP_OBJECT (restore_file_selection, handlebox4, "handlebox4");
  GLADE_HOOKUP_OBJECT (restore_file_selection, menubar2, "menubar2");
  GLADE_HOOKUP_OBJECT (restore_file_selection, menubar2_uiinfo[0].widget, "file2");
  GLADE_HOOKUP_OBJECT (restore_file_selection, file2_menu_uiinfo[0].widget, "new1");
  GLADE_HOOKUP_OBJECT (restore_file_selection, file2_menu_uiinfo[1].widget, "open1");
  GLADE_HOOKUP_OBJECT (restore_file_selection, file2_menu_uiinfo[2].widget, "save1");
  GLADE_HOOKUP_OBJECT (restore_file_selection, file2_menu_uiinfo[3].widget, "save_as1");
  GLADE_HOOKUP_OBJECT (restore_file_selection, file2_menu_uiinfo[4].widget, "separator4");
  GLADE_HOOKUP_OBJECT (restore_file_selection, file2_menu_uiinfo[5].widget, "quit1");
  GLADE_HOOKUP_OBJECT (restore_file_selection, menubar2_uiinfo[1].widget, "edit2");
  GLADE_HOOKUP_OBJECT (restore_file_selection, edit2_menu_uiinfo[0].widget, "cut2");
  GLADE_HOOKUP_OBJECT (restore_file_selection, edit2_menu_uiinfo[1].widget, "copy2");
  GLADE_HOOKUP_OBJECT (restore_file_selection, edit2_menu_uiinfo[2].widget, "paste2");
  GLADE_HOOKUP_OBJECT (restore_file_selection, edit2_menu_uiinfo[3].widget, "clear2");
  GLADE_HOOKUP_OBJECT (restore_file_selection, edit2_menu_uiinfo[4].widget, "separator5");
  GLADE_HOOKUP_OBJECT (restore_file_selection, edit2_menu_uiinfo[5].widget, "properties1");
  GLADE_HOOKUP_OBJECT (restore_file_selection, edit2_menu_uiinfo[6].widget, "separator6");
  GLADE_HOOKUP_OBJECT (restore_file_selection, edit2_menu_uiinfo[7].widget, "preferences2");
  GLADE_HOOKUP_OBJECT (restore_file_selection, menubar2_uiinfo[2].widget, "view1");
  GLADE_HOOKUP_OBJECT (restore_file_selection, menubar2_uiinfo[3].widget, "help2");
  GLADE_HOOKUP_OBJECT (restore_file_selection, help2_menu_uiinfo[0].widget, "about2");
  GLADE_HOOKUP_OBJECT (restore_file_selection, handlebox3, "handlebox3");
  GLADE_HOOKUP_OBJECT (restore_file_selection, toolbar3, "toolbar3");
  GLADE_HOOKUP_OBJECT (restore_file_selection, restore_up_button, "restore_up_button");
  GLADE_HOOKUP_OBJECT (restore_file_selection, restore_add_button, "restore_add_button");
  GLADE_HOOKUP_OBJECT (restore_file_selection, restore_remove_button, "restore_remove_button");
  GLADE_HOOKUP_OBJECT (restore_file_selection, hbox38, "hbox38");
  GLADE_HOOKUP_OBJECT (restore_file_selection, label88, "label88");
  GLADE_HOOKUP_OBJECT (restore_file_selection, restore_dir, "restore_dir");
  GLADE_HOOKUP_OBJECT (restore_file_selection, hpaned1, "hpaned1");
  GLADE_HOOKUP_OBJECT (restore_file_selection, tree, "tree");
  GLADE_HOOKUP_OBJECT (restore_file_selection, scrolled, "scrolled");
  GLADE_HOOKUP_OBJECT (restore_file_selection, hbox44, "hbox44");
  GLADE_HOOKUP_OBJECT (restore_file_selection, FilesSelected, "FilesSelected");
  GLADE_HOOKUP_OBJECT (restore_file_selection, restore_select_ok, "restore_select_ok");
  GLADE_HOOKUP_OBJECT (restore_file_selection, label152, "label152");
  GLADE_HOOKUP_OBJECT (restore_file_selection, restore_select_cancel, "restore_select_cancel");
  GLADE_HOOKUP_OBJECT (restore_file_selection, label1001, "label1001");

  gtk_window_add_accel_group (GTK_WINDOW (restore_file_selection), accel_group);

  return restore_file_selection;
}

GtkWidget*
create_label_dialog (void)
{
  GtkWidget *label_dialog;
  GtkWidget *dialog_vbox9;
  GtkWidget *vbox16;
  GtkWidget *label106;
  GtkWidget *hbox45;
  GtkWidget *label107;
  GtkWidget *label_combo_storage;
  GList *label_combo_storage_items = NULL;
  GtkWidget *entry26;
  GtkWidget *hbox46;
  GtkWidget *label109;
  GtkWidget *label_combo_pool;
  GList *label_combo_pool_items = NULL;
  GtkWidget *entry27;
  GtkWidget *hbox47;
  GtkWidget *label111;
  GtkWidget *label_entry_volume;
  GtkWidget *hbox48;
  GtkWidget *slot1;
  GtkObject *label_slot_adj;
  GtkWidget *label_slot;
  GtkWidget *label113;
  GtkWidget *dialog_action_area8;
  GtkWidget *hbuttonbox3;
  GtkWidget *label_ok;
  GtkWidget *label_cancel;

  label_dialog = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (label_dialog), _("Label a Volume"));
  gtk_window_set_modal (GTK_WINDOW (label_dialog), TRUE);
  gtk_window_set_type_hint (GTK_WINDOW (label_dialog), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox9 = GTK_DIALOG (label_dialog)->vbox;
  gtk_widget_show (dialog_vbox9);

  vbox16 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox16);
  gtk_box_pack_start (GTK_BOX (dialog_vbox9), vbox16, FALSE, TRUE, 0);

  label106 = gtk_label_new (_("Label a Volume"));
  gtk_widget_show (label106);
  gtk_box_pack_start (GTK_BOX (vbox16), label106, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label106), GTK_JUSTIFY_CENTER);
  gtk_misc_set_padding (GTK_MISC (label106), 0, 9);

  hbox45 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox45);
  gtk_box_pack_start (GTK_BOX (vbox16), hbox45, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox45), 5);

  label107 = gtk_label_new (_("Storage:"));
  gtk_widget_show (label107);
  gtk_box_pack_start (GTK_BOX (hbox45), label107, TRUE, TRUE, 0);
  gtk_label_set_justify (GTK_LABEL (label107), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (label107), 0.15, 0.5);

  label_combo_storage = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (label_combo_storage)->popwin),
                     "GladeParentKey", label_combo_storage);
  gtk_widget_show (label_combo_storage);
  gtk_box_pack_start (GTK_BOX (hbox45), label_combo_storage, TRUE, TRUE, 15);
  gtk_combo_set_value_in_list (GTK_COMBO (label_combo_storage), TRUE, FALSE);
  label_combo_storage_items = g_list_append (label_combo_storage_items, (gpointer) "");
  label_combo_storage_items = g_list_append (label_combo_storage_items, (gpointer) "");
  gtk_combo_set_popdown_strings (GTK_COMBO (label_combo_storage), label_combo_storage_items);
  g_list_free (label_combo_storage_items);

  entry26 = GTK_COMBO (label_combo_storage)->entry;
  gtk_widget_show (entry26);
  gtk_editable_set_editable (GTK_EDITABLE (entry26), FALSE);

  hbox46 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox46);
  gtk_box_pack_start (GTK_BOX (vbox16), hbox46, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox46), 5);

  label109 = gtk_label_new (_("Pool:"));
  gtk_widget_show (label109);
  gtk_box_pack_start (GTK_BOX (hbox46), label109, TRUE, TRUE, 0);
  gtk_misc_set_alignment (GTK_MISC (label109), 0.12, 0.5);

  label_combo_pool = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (label_combo_pool)->popwin),
                     "GladeParentKey", label_combo_pool);
  gtk_widget_show (label_combo_pool);
  gtk_box_pack_start (GTK_BOX (hbox46), label_combo_pool, TRUE, TRUE, 14);
  gtk_combo_set_value_in_list (GTK_COMBO (label_combo_pool), TRUE, FALSE);
  label_combo_pool_items = g_list_append (label_combo_pool_items, (gpointer) "");
  label_combo_pool_items = g_list_append (label_combo_pool_items, (gpointer) "");
  gtk_combo_set_popdown_strings (GTK_COMBO (label_combo_pool), label_combo_pool_items);
  g_list_free (label_combo_pool_items);

  entry27 = GTK_COMBO (label_combo_pool)->entry;
  gtk_widget_show (entry27);
  gtk_editable_set_editable (GTK_EDITABLE (entry27), FALSE);

  hbox47 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox47);
  gtk_box_pack_start (GTK_BOX (vbox16), hbox47, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox47), 5);

  label111 = gtk_label_new (_("Volume Name:"));
  gtk_widget_show (label111);
  gtk_box_pack_start (GTK_BOX (hbox47), label111, TRUE, TRUE, 0);
  gtk_misc_set_alignment (GTK_MISC (label111), 0.17, 0.5);

  label_entry_volume = gtk_entry_new ();
  gtk_widget_show (label_entry_volume);
  gtk_box_pack_start (GTK_BOX (hbox47), label_entry_volume, TRUE, TRUE, 0);

  hbox48 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox48);
  gtk_box_pack_start (GTK_BOX (vbox16), hbox48, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox48), 5);

  slot1 = gtk_label_new (_("Slot:"));
  gtk_widget_show (slot1);
  gtk_box_pack_start (GTK_BOX (hbox48), slot1, FALSE, TRUE, 0);
  gtk_misc_set_alignment (GTK_MISC (slot1), 0.09, 0.5);

  label_slot_adj = gtk_adjustment_new (0, 0, 10000, 1, 10, 10);
  label_slot = gtk_spin_button_new (GTK_ADJUSTMENT (label_slot_adj), 1, 0);
  gtk_widget_show (label_slot);
  gtk_box_pack_start (GTK_BOX (hbox48), label_slot, TRUE, TRUE, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (label_slot), TRUE);

  label113 = gtk_label_new (_("   "));
  gtk_widget_show (label113);
  gtk_box_pack_start (GTK_BOX (vbox16), label113, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label113), GTK_JUSTIFY_CENTER);

  dialog_action_area8 = GTK_DIALOG (label_dialog)->action_area;
  gtk_widget_show (dialog_action_area8);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area8), GTK_BUTTONBOX_END);

  hbuttonbox3 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox3);
  gtk_container_add (GTK_CONTAINER (dialog_action_area8), hbuttonbox3);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox3), GTK_BUTTONBOX_END);
  gtk_box_set_spacing (GTK_BOX (hbuttonbox3), 8);

  label_ok = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (label_ok);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), label_ok);
  GTK_WIDGET_SET_FLAGS (label_ok, GTK_CAN_DEFAULT);

  label_cancel = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (label_cancel);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), label_cancel);
  GTK_WIDGET_SET_FLAGS (label_cancel, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) label_ok, "clicked",
                    G_CALLBACK (on_label_ok_clicked),
                    NULL);
  g_signal_connect ((gpointer) label_cancel, "clicked",
                    G_CALLBACK (on_label_cancel_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (label_dialog, label_dialog, "label_dialog");
  GLADE_HOOKUP_OBJECT_NO_REF (label_dialog, dialog_vbox9, "dialog_vbox9");
  GLADE_HOOKUP_OBJECT (label_dialog, vbox16, "vbox16");
  GLADE_HOOKUP_OBJECT (label_dialog, label106, "label106");
  GLADE_HOOKUP_OBJECT (label_dialog, hbox45, "hbox45");
  GLADE_HOOKUP_OBJECT (label_dialog, label107, "label107");
  GLADE_HOOKUP_OBJECT (label_dialog, label_combo_storage, "label_combo_storage");
  GLADE_HOOKUP_OBJECT (label_dialog, entry26, "entry26");
  GLADE_HOOKUP_OBJECT (label_dialog, hbox46, "hbox46");
  GLADE_HOOKUP_OBJECT (label_dialog, label109, "label109");
  GLADE_HOOKUP_OBJECT (label_dialog, label_combo_pool, "label_combo_pool");
  GLADE_HOOKUP_OBJECT (label_dialog, entry27, "entry27");
  GLADE_HOOKUP_OBJECT (label_dialog, hbox47, "hbox47");
  GLADE_HOOKUP_OBJECT (label_dialog, label111, "label111");
  GLADE_HOOKUP_OBJECT (label_dialog, label_entry_volume, "label_entry_volume");
  GLADE_HOOKUP_OBJECT (label_dialog, hbox48, "hbox48");
  GLADE_HOOKUP_OBJECT (label_dialog, slot1, "slot1");
  GLADE_HOOKUP_OBJECT (label_dialog, label_slot, "label_slot");
  GLADE_HOOKUP_OBJECT (label_dialog, label113, "label113");
  GLADE_HOOKUP_OBJECT_NO_REF (label_dialog, dialog_action_area8, "dialog_action_area8");
  GLADE_HOOKUP_OBJECT (label_dialog, hbuttonbox3, "hbuttonbox3");
  GLADE_HOOKUP_OBJECT (label_dialog, label_ok, "label_ok");
  GLADE_HOOKUP_OBJECT (label_dialog, label_cancel, "label_cancel");

  return label_dialog;
}

GtkWidget*
create_RestoreDialog (void)
{
  GtkWidget *RestoreDialog;
  GtkWidget *dialog_vbox10;
  GtkWidget *vbox17;
  GtkWidget *vbox18;
  GtkWidget *label119;
  GtkWidget *alignment3;
  GtkWidget *hbox50;
  GtkWidget *hbox51;
  GtkWidget *label120;
  GtkWidget *combo_restore_job;
  GList *combo_restore_job_items = NULL;
  GtkWidget *restore_job_entry;
  GtkWidget *label122;
  GtkWidget *hbox52;
  GtkWidget *label125;
  GtkWidget *combo_restore_client;
  GList *combo_restore_client_items = NULL;
  GtkWidget *restore_client_entry;
  GtkWidget *label127;
  GtkWidget *hbox53;
  GtkWidget *label128;
  GtkWidget *combo_restore_fileset;
  GList *combo_restore_fileset_items = NULL;
  GtkWidget *restore_fileset_entry;
  GtkWidget *label130;
  GtkWidget *hbox55;
  GtkWidget *label135;
  GtkWidget *combo_restore_pool;
  GList *combo_restore_pool_items = NULL;
  GtkWidget *restore_pool_entry;
  GtkWidget *label138;
  GtkWidget *hbox56;
  GtkWidget *label139;
  GtkWidget *combo_restore_storage;
  GList *combo_restore_storage_items = NULL;
  GtkWidget *restore_storage_entry;
  GtkWidget *label142;
  GtkWidget *hbox59;
  GtkWidget *label148;
  GtkWidget *restore_before_entry;
  GtkWidget *label149;
  GtkWidget *label150;
  GtkWidget *dialog_action_area9;
  GtkWidget *helpbutton1;
  GtkWidget *select_files_button;
  GtkWidget *alignment2;
  GtkWidget *hbox49;
  GtkWidget *image1;
  GtkWidget *restore_select_button;
  GtkWidget *restore_cancel;

  RestoreDialog = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (RestoreDialog), _("Restore Files Dialog"));
  gtk_window_set_default_size (GTK_WINDOW (RestoreDialog), 300, 200);
  gtk_window_set_type_hint (GTK_WINDOW (RestoreDialog), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox10 = GTK_DIALOG (RestoreDialog)->vbox;
  gtk_widget_show (dialog_vbox10);

  vbox17 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox17);
  gtk_box_pack_start (GTK_BOX (dialog_vbox10), vbox17, TRUE, TRUE, 0);

  vbox18 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox18);
  gtk_box_pack_start (GTK_BOX (vbox17), vbox18, TRUE, TRUE, 0);

  label119 = gtk_label_new (_("Restore Files"));
  gtk_widget_show (label119);
  gtk_box_pack_start (GTK_BOX (vbox18), label119, FALSE, FALSE, 2);
  gtk_label_set_justify (GTK_LABEL (label119), GTK_JUSTIFY_CENTER);
  gtk_misc_set_padding (GTK_MISC (label119), 0, 9);

  alignment3 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment3);
  gtk_box_pack_start (GTK_BOX (vbox18), alignment3, FALSE, FALSE, 2);

  hbox50 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox50);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox50);

  hbox51 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox51);
  gtk_box_pack_start (GTK_BOX (hbox50), hbox51, TRUE, TRUE, 0);

  label120 = gtk_label_new (_("Job:"));
  gtk_widget_show (label120);
  gtk_box_pack_start (GTK_BOX (hbox51), label120, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label120, 66, 16);
  gtk_label_set_justify (GTK_LABEL (label120), GTK_JUSTIFY_RIGHT);

  combo_restore_job = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo_restore_job)->popwin),
                     "GladeParentKey", combo_restore_job);
  gtk_widget_show (combo_restore_job);
  gtk_box_pack_start (GTK_BOX (hbox51), combo_restore_job, TRUE, TRUE, 1);
  gtk_combo_set_value_in_list (GTK_COMBO (combo_restore_job), TRUE, FALSE);
  combo_restore_job_items = g_list_append (combo_restore_job_items, (gpointer) "");
  gtk_combo_set_popdown_strings (GTK_COMBO (combo_restore_job), combo_restore_job_items);
  g_list_free (combo_restore_job_items);

  restore_job_entry = GTK_COMBO (combo_restore_job)->entry;
  gtk_widget_show (restore_job_entry);
  gtk_editable_set_editable (GTK_EDITABLE (restore_job_entry), FALSE);

  label122 = gtk_label_new ("");
  gtk_widget_show (label122);
  gtk_box_pack_start (GTK_BOX (hbox51), label122, FALSE, FALSE, 27);
  gtk_label_set_justify (GTK_LABEL (label122), GTK_JUSTIFY_CENTER);

  hbox52 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox52);
  gtk_box_pack_start (GTK_BOX (vbox18), hbox52, TRUE, TRUE, 0);

  label125 = gtk_label_new (_("Client:"));
  gtk_widget_show (label125);
  gtk_box_pack_start (GTK_BOX (hbox52), label125, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label125, 66, 16);
  gtk_label_set_justify (GTK_LABEL (label125), GTK_JUSTIFY_RIGHT);

  combo_restore_client = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo_restore_client)->popwin),
                     "GladeParentKey", combo_restore_client);
  gtk_widget_show (combo_restore_client);
  gtk_box_pack_start (GTK_BOX (hbox52), combo_restore_client, TRUE, TRUE, 1);
  gtk_combo_set_value_in_list (GTK_COMBO (combo_restore_client), TRUE, FALSE);
  combo_restore_client_items = g_list_append (combo_restore_client_items, (gpointer) "");
  gtk_combo_set_popdown_strings (GTK_COMBO (combo_restore_client), combo_restore_client_items);
  g_list_free (combo_restore_client_items);

  restore_client_entry = GTK_COMBO (combo_restore_client)->entry;
  gtk_widget_show (restore_client_entry);
  gtk_editable_set_editable (GTK_EDITABLE (restore_client_entry), FALSE);

  label127 = gtk_label_new (_(" "));
  gtk_widget_show (label127);
  gtk_box_pack_start (GTK_BOX (hbox52), label127, FALSE, FALSE, 25);
  gtk_label_set_justify (GTK_LABEL (label127), GTK_JUSTIFY_CENTER);

  hbox53 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox53);
  gtk_box_pack_start (GTK_BOX (vbox18), hbox53, TRUE, TRUE, 2);

  label128 = gtk_label_new (_("FileSet: "));
  gtk_widget_show (label128);
  gtk_box_pack_start (GTK_BOX (hbox53), label128, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label128, 66, 16);
  gtk_label_set_justify (GTK_LABEL (label128), GTK_JUSTIFY_RIGHT);

  combo_restore_fileset = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo_restore_fileset)->popwin),
                     "GladeParentKey", combo_restore_fileset);
  gtk_widget_show (combo_restore_fileset);
  gtk_box_pack_start (GTK_BOX (hbox53), combo_restore_fileset, TRUE, TRUE, 0);
  gtk_combo_set_value_in_list (GTK_COMBO (combo_restore_fileset), TRUE, FALSE);
  combo_restore_fileset_items = g_list_append (combo_restore_fileset_items, (gpointer) "");
  gtk_combo_set_popdown_strings (GTK_COMBO (combo_restore_fileset), combo_restore_fileset_items);
  g_list_free (combo_restore_fileset_items);

  restore_fileset_entry = GTK_COMBO (combo_restore_fileset)->entry;
  gtk_widget_show (restore_fileset_entry);
  gtk_editable_set_editable (GTK_EDITABLE (restore_fileset_entry), FALSE);

  label130 = gtk_label_new (_("  "));
  gtk_widget_show (label130);
  gtk_box_pack_start (GTK_BOX (hbox53), label130, FALSE, FALSE, 23);
  gtk_label_set_justify (GTK_LABEL (label130), GTK_JUSTIFY_CENTER);

  hbox55 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox55);
  gtk_box_pack_start (GTK_BOX (vbox18), hbox55, TRUE, TRUE, 2);

  label135 = gtk_label_new (_("Pool:"));
  gtk_widget_show (label135);
  gtk_box_pack_start (GTK_BOX (hbox55), label135, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label135, 66, 16);
  gtk_label_set_justify (GTK_LABEL (label135), GTK_JUSTIFY_CENTER);

  combo_restore_pool = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo_restore_pool)->popwin),
                     "GladeParentKey", combo_restore_pool);
  gtk_widget_show (combo_restore_pool);
  gtk_box_pack_start (GTK_BOX (hbox55), combo_restore_pool, TRUE, TRUE, 0);
  gtk_combo_set_value_in_list (GTK_COMBO (combo_restore_pool), TRUE, FALSE);
  combo_restore_pool_items = g_list_append (combo_restore_pool_items, (gpointer) "");
  combo_restore_pool_items = g_list_append (combo_restore_pool_items, (gpointer) "");
  gtk_combo_set_popdown_strings (GTK_COMBO (combo_restore_pool), combo_restore_pool_items);
  g_list_free (combo_restore_pool_items);

  restore_pool_entry = GTK_COMBO (combo_restore_pool)->entry;
  gtk_widget_show (restore_pool_entry);
  gtk_editable_set_editable (GTK_EDITABLE (restore_pool_entry), FALSE);

  label138 = gtk_label_new (_("   "));
  gtk_widget_show (label138);
  gtk_box_pack_start (GTK_BOX (hbox55), label138, FALSE, FALSE, 21);
  gtk_label_set_justify (GTK_LABEL (label138), GTK_JUSTIFY_CENTER);

  hbox56 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox56);
  gtk_box_pack_start (GTK_BOX (vbox18), hbox56, TRUE, TRUE, 0);

  label139 = gtk_label_new (_("Storage:"));
  gtk_widget_show (label139);
  gtk_box_pack_start (GTK_BOX (hbox56), label139, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label139, 66, 16);
  gtk_label_set_justify (GTK_LABEL (label139), GTK_JUSTIFY_CENTER);

  combo_restore_storage = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo_restore_storage)->popwin),
                     "GladeParentKey", combo_restore_storage);
  gtk_widget_show (combo_restore_storage);
  gtk_box_pack_start (GTK_BOX (hbox56), combo_restore_storage, TRUE, TRUE, 0);
  gtk_combo_set_value_in_list (GTK_COMBO (combo_restore_storage), TRUE, FALSE);
  combo_restore_storage_items = g_list_append (combo_restore_storage_items, (gpointer) "");
  combo_restore_storage_items = g_list_append (combo_restore_storage_items, (gpointer) "");
  gtk_combo_set_popdown_strings (GTK_COMBO (combo_restore_storage), combo_restore_storage_items);
  g_list_free (combo_restore_storage_items);

  restore_storage_entry = GTK_COMBO (combo_restore_storage)->entry;
  gtk_widget_show (restore_storage_entry);
  gtk_editable_set_editable (GTK_EDITABLE (restore_storage_entry), FALSE);

  label142 = gtk_label_new (_("   "));
  gtk_widget_show (label142);
  gtk_box_pack_start (GTK_BOX (hbox56), label142, FALSE, FALSE, 21);
  gtk_label_set_justify (GTK_LABEL (label142), GTK_JUSTIFY_CENTER);

  hbox59 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox59);
  gtk_box_pack_start (GTK_BOX (vbox17), hbox59, TRUE, TRUE, 0);

  label148 = gtk_label_new (_("Before:"));
  gtk_widget_show (label148);
  gtk_box_pack_start (GTK_BOX (hbox59), label148, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label148, 66, 16);
  gtk_label_set_justify (GTK_LABEL (label148), GTK_JUSTIFY_CENTER);

  restore_before_entry = gtk_entry_new ();
  gtk_widget_show (restore_before_entry);
  gtk_box_pack_start (GTK_BOX (hbox59), restore_before_entry, TRUE, TRUE, 0);

  label149 = gtk_label_new (_("   "));
  gtk_widget_show (label149);
  gtk_box_pack_start (GTK_BOX (hbox59), label149, FALSE, FALSE, 53);
  gtk_label_set_justify (GTK_LABEL (label149), GTK_JUSTIFY_CENTER);

  label150 = gtk_label_new (_("   "));
  gtk_widget_show (label150);
  gtk_box_pack_start (GTK_BOX (vbox17), label150, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label150), GTK_JUSTIFY_CENTER);

  dialog_action_area9 = GTK_DIALOG (RestoreDialog)->action_area;
  gtk_widget_show (dialog_action_area9);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area9), GTK_BUTTONBOX_END);

  helpbutton1 = gtk_button_new_from_stock ("gtk-help");
  gtk_widget_show (helpbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (RestoreDialog), helpbutton1, GTK_RESPONSE_HELP);
  GTK_WIDGET_SET_FLAGS (helpbutton1, GTK_CAN_DEFAULT);

  select_files_button = gtk_button_new ();
  gtk_widget_show (select_files_button);
  gtk_dialog_add_action_widget (GTK_DIALOG (RestoreDialog), select_files_button, 0);
  GTK_WIDGET_SET_FLAGS (select_files_button, GTK_CAN_DEFAULT);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (select_files_button), alignment2);

  hbox49 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox49);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox49);

  image1 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox49), image1, FALSE, FALSE, 0);

  restore_select_button = gtk_label_new_with_mnemonic (_("Select Files"));
  gtk_widget_show (restore_select_button);
  gtk_box_pack_start (GTK_BOX (hbox49), restore_select_button, FALSE, FALSE, 0);

  restore_cancel = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (restore_cancel);
  gtk_dialog_add_action_widget (GTK_DIALOG (RestoreDialog), restore_cancel, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (restore_cancel, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) restore_job_entry, "changed",
                    G_CALLBACK (on_restore_job_entry_changed),
                    NULL);
  g_signal_connect ((gpointer) select_files_button, "clicked",
                    G_CALLBACK (on_select_files_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) restore_cancel, "clicked",
                    G_CALLBACK (on_restore_cancel_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (RestoreDialog, RestoreDialog, "RestoreDialog");
  GLADE_HOOKUP_OBJECT_NO_REF (RestoreDialog, dialog_vbox10, "dialog_vbox10");
  GLADE_HOOKUP_OBJECT (RestoreDialog, vbox17, "vbox17");
  GLADE_HOOKUP_OBJECT (RestoreDialog, vbox18, "vbox18");
  GLADE_HOOKUP_OBJECT (RestoreDialog, label119, "label119");
  GLADE_HOOKUP_OBJECT (RestoreDialog, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (RestoreDialog, hbox50, "hbox50");
  GLADE_HOOKUP_OBJECT (RestoreDialog, hbox51, "hbox51");
  GLADE_HOOKUP_OBJECT (RestoreDialog, label120, "label120");
  GLADE_HOOKUP_OBJECT (RestoreDialog, combo_restore_job, "combo_restore_job");
  GLADE_HOOKUP_OBJECT (RestoreDialog, restore_job_entry, "restore_job_entry");
  GLADE_HOOKUP_OBJECT (RestoreDialog, label122, "label122");
  GLADE_HOOKUP_OBJECT (RestoreDialog, hbox52, "hbox52");
  GLADE_HOOKUP_OBJECT (RestoreDialog, label125, "label125");
  GLADE_HOOKUP_OBJECT (RestoreDialog, combo_restore_client, "combo_restore_client");
  GLADE_HOOKUP_OBJECT (RestoreDialog, restore_client_entry, "restore_client_entry");
  GLADE_HOOKUP_OBJECT (RestoreDialog, label127, "label127");
  GLADE_HOOKUP_OBJECT (RestoreDialog, hbox53, "hbox53");
  GLADE_HOOKUP_OBJECT (RestoreDialog, label128, "label128");
  GLADE_HOOKUP_OBJECT (RestoreDialog, combo_restore_fileset, "combo_restore_fileset");
  GLADE_HOOKUP_OBJECT (RestoreDialog, restore_fileset_entry, "restore_fileset_entry");
  GLADE_HOOKUP_OBJECT (RestoreDialog, label130, "label130");
  GLADE_HOOKUP_OBJECT (RestoreDialog, hbox55, "hbox55");
  GLADE_HOOKUP_OBJECT (RestoreDialog, label135, "label135");
  GLADE_HOOKUP_OBJECT (RestoreDialog, combo_restore_pool, "combo_restore_pool");
  GLADE_HOOKUP_OBJECT (RestoreDialog, restore_pool_entry, "restore_pool_entry");
  GLADE_HOOKUP_OBJECT (RestoreDialog, label138, "label138");
  GLADE_HOOKUP_OBJECT (RestoreDialog, hbox56, "hbox56");
  GLADE_HOOKUP_OBJECT (RestoreDialog, label139, "label139");
  GLADE_HOOKUP_OBJECT (RestoreDialog, combo_restore_storage, "combo_restore_storage");
  GLADE_HOOKUP_OBJECT (RestoreDialog, restore_storage_entry, "restore_storage_entry");
  GLADE_HOOKUP_OBJECT (RestoreDialog, label142, "label142");
  GLADE_HOOKUP_OBJECT (RestoreDialog, hbox59, "hbox59");
  GLADE_HOOKUP_OBJECT (RestoreDialog, label148, "label148");
  GLADE_HOOKUP_OBJECT (RestoreDialog, restore_before_entry, "restore_before_entry");
  GLADE_HOOKUP_OBJECT (RestoreDialog, label149, "label149");
  GLADE_HOOKUP_OBJECT (RestoreDialog, label150, "label150");
  GLADE_HOOKUP_OBJECT_NO_REF (RestoreDialog, dialog_action_area9, "dialog_action_area9");
  GLADE_HOOKUP_OBJECT (RestoreDialog, helpbutton1, "helpbutton1");
  GLADE_HOOKUP_OBJECT (RestoreDialog, select_files_button, "select_files_button");
  GLADE_HOOKUP_OBJECT (RestoreDialog, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (RestoreDialog, hbox49, "hbox49");
  GLADE_HOOKUP_OBJECT (RestoreDialog, image1, "image1");
  GLADE_HOOKUP_OBJECT (RestoreDialog, restore_select_button, "restore_select_button");
  GLADE_HOOKUP_OBJECT (RestoreDialog, restore_cancel, "restore_cancel");

  return RestoreDialog;
}

GtkWidget*
create_progress_dialog (void)
{
  GtkWidget *progress_dialog;
  GtkWidget *dialog_vbox11;
  GtkWidget *vbox19;
  GtkWidget *label1002;
  GtkWidget *label1003;
  GtkWidget *progressbar1;
  GtkWidget *label1004;
  GtkWidget *dialog_action_area10;
  GtkWidget *closebutton1;

  progress_dialog = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (progress_dialog), _("Progress"));
  gtk_window_set_type_hint (GTK_WINDOW (progress_dialog), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox11 = GTK_DIALOG (progress_dialog)->vbox;
  gtk_widget_show (dialog_vbox11);

  vbox19 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox19);
  gtk_box_pack_start (GTK_BOX (dialog_vbox11), vbox19, TRUE, TRUE, 0);

  label1002 = gtk_label_new ("");
  gtk_widget_show (label1002);
  gtk_box_pack_start (GTK_BOX (vbox19), label1002, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label1002, 0, 43);

  label1003 = gtk_label_new ("");
  gtk_widget_show (label1003);
  gtk_box_pack_start (GTK_BOX (vbox19), label1003, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label1003, 0, 36);

  progressbar1 = gtk_progress_bar_new ();
  gtk_widget_show (progressbar1);
  gtk_box_pack_start (GTK_BOX (vbox19), progressbar1, TRUE, FALSE, 0);
  gtk_widget_set_size_request (progressbar1, 150, 33);

  label1004 = gtk_label_new ("");
  gtk_widget_show (label1004);
  gtk_box_pack_start (GTK_BOX (vbox19), label1004, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label1004, 0, 52);

  dialog_action_area10 = GTK_DIALOG (progress_dialog)->action_area;
  gtk_widget_show (dialog_action_area10);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area10), GTK_BUTTONBOX_END);

  closebutton1 = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_show (closebutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (progress_dialog), closebutton1, GTK_RESPONSE_CLOSE);
  GTK_WIDGET_SET_FLAGS (closebutton1, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (progress_dialog, progress_dialog, "progress_dialog");
  GLADE_HOOKUP_OBJECT_NO_REF (progress_dialog, dialog_vbox11, "dialog_vbox11");
  GLADE_HOOKUP_OBJECT (progress_dialog, vbox19, "vbox19");
  GLADE_HOOKUP_OBJECT (progress_dialog, label1002, "label1002");
  GLADE_HOOKUP_OBJECT (progress_dialog, label1003, "label1003");
  GLADE_HOOKUP_OBJECT (progress_dialog, progressbar1, "progressbar1");
  GLADE_HOOKUP_OBJECT (progress_dialog, label1004, "label1004");
  GLADE_HOOKUP_OBJECT_NO_REF (progress_dialog, dialog_action_area10, "dialog_action_area10");
  GLADE_HOOKUP_OBJECT (progress_dialog, closebutton1, "closebutton1");

  return progress_dialog;
}

