/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_console (void);
GtkWidget* create_about1 (void);
GtkWidget* create_SelectDirectorDialog (void);
GtkWidget* create_RunDialog (void);
GtkWidget* create_restore_file_selection (void);
GtkWidget* create_label_dialog (void);
GtkWidget* create_RestoreDialog (void);
GtkWidget* create_progress_dialog (void);
