#!/bin/sh
#
# This script prepares the source for compiling check_bacula
#
# It's more or less untested, though.
#  Submitted by Arno Lehmann <al@its-lehmann.de>
#

# Save configure
mv -uiv configure configure.without_check_bacula

# Modify ./configure
sed -e 's/\(ac_config_files=".*$PFILES\)"/\1 src\/check_bacula\/Makefile"/' -e 's/\(^ *# Handling of arguments.*$\)/\1\n  "src\/check_bacula\/Makefile" ) CONFIG_FILES="$CONFIG_FILES src\/check_bacula\/Makefile" ;;/' configure.without_check_bacula > configure
chmod a+x configure

# extract check_bacula source
tar xzCf src examples/nagios/nagios_plugin_check_bacula.tgz

echo "Now you can run ./configure with your usual options. Afterwards, use
'make' to create your binaries. Then you can run 'make' in
src/check_bacula to create that program.

If you encounter problems, you'll have to setup the Bacula source manually.
The original configure script has been saved to configure.without_check_bacula

Note that check_bacula does not support TLS and is an unsupported add-on to
Bacula. Even if it's not part of the core Bacula programs, questions can be
asked at the bacula-users mailing list.

Bacula is a Trademark of Kern Sibbald. Bacula and the accompanying programs
are open source. See the LICENSE file for more information.
"
