#!/bin/bash

mv debian/tmp/etc/bacula/scripts/mtx-changer \
	debian/tmp/etc/bacula/scripts/mtx-changer.orig

sed -e 's%MTX=mtx%MTX=/usr/sbin/mtx%' \
	< debian/tmp/etc/bacula/scripts/mtx-changer.orig \
	> debian/tmp/etc/bacula/scripts/mtx-changer

chmod 755 debian/tmp/etc/bacula/scripts/mtx-changer
