#!/bin/sh

set -e


if [ -z "$1" -o -z "$2" ]; then
	test -n "$DH_VERBOSE" && echo "Params missing!" >/dev/fd/2;
	exit 1
fi
	
cat $1 | sed -e s~`uname -n | cut -d '.' -f 1`~@hostname@~g | sed -r -f `dirname $0`/fix_config.sed > $2
