#!/bin/sh

set -e


if [ -z "$1" -o -z "$2" ]; then
	test -n "$DH_VERBOSE" && echo "Params missing!" >/dev/fd/2;
	exit 1
fi
	
cat $1 | sed -e s~`hostname`~@hostname@~g | \
	sed -e "s~Address =`hostname`~Address = @fqdn@~g" | \
	sed -f `dirname $0`/fix_director.sed | \
	sed -f `dirname $0`/fix_config.sed > $2
