
Windows/cygwin compiling notes:
 - Download latest depkgs-win32 code.
 - See <bacula-source>/src/win32/README.win32

GTK/Linux (and *nix) compiling notes:
 - Download www.wxwidgets.org wxWidgets code version 2.4.2
 - Build and install the above using --disable-universal configure
    option.
 - Use ./configure --enable-bwx-console for the Bacula build
   It will then be built and installed automatically with the
   other programs.
 - Edit the bwx-console.conf in the current directory to have the
   correct values for your Director (name, IP address, password).
