
default:
	env MAKEFLAGS= nmake CFG="baculafd - Win32 Release" /f baculafd.mak
clean:
	env MAKEFLAGS= nmake CFG="baculafd - Win32 Release" /f baculafd.mak clean
	rm -f baculafd.plg baculafd.opt baculafd.ncb
