#!/bin/sh
#
# shell script to grant privileges to the bacula database
#
bindir=@SQL_BINDIR@

if test -z "$DBUSER"; then DBUSER=bacula; fi

if $bindir/psql $* -f - <<END-OF-DATA
\c bacula

create user bacula;
create user $DBUSER password '$DBPASS';

-- for tables
grant all on unsavedfiles to $DBUSER;
grant all on basefiles    to $DBUSER;
grant all on jobmedia     to $DBUSER;
grant all on file         to $DBUSER;
grant all on job          to $DBUSER;
grant all on media        to $DBUSER;
grant all on client       to $DBUSER;
grant all on pool         to $DBUSER;
grant all on fileset      to $DBUSER;
grant all on path         to $DBUSER;
grant all on filename     to $DBUSER;
grant all on counters     to $DBUSER;
grant all on version      to $DBUSER;

-- for sequences on those tables
grant select, update on filename_filenameid_seq to $DBUSER;
grant select, update on path_pathid_seq         to $DBUSER;
grant select, update on fileset_filesetid_seq   to $DBUSER;
grant select, update on pool_poolid_seq         to $DBUSER;
grant select, update on client_clientid_seq     to $DBUSER;
grant select, update on media_mediaid_seq       to $DBUSER;
grant select, update on job_jobid_seq           to $DBUSER;
grant select, update on file_fileid_seq         to $DBUSER;
grant select, update on jobmedia_jobmediaid_seq to $DBUSER;
grant select, update on basefiles_baseid_seq    to $DBUSER;

END-OF-DATA
then
then
   echo "Privileges for bacula granted."
   exit 0
else
   echo "Error creating privileges."
   exit 1
fi

