#!/bin/sh
#
# This script dumps your Bacula catalog in ASCII format
# by Jose Luis Tallon <jltallon@adv-solutions.net>
# based on work by Kern Sibbald.
#
WORKDIR=/var/lib/bacula
DATAFILE=bacula.sql


FLAVOR="`cat /etc/bacula/bacula_flavor`"
if [ -z "$FLAVOR" ]; then
	echo "ERROR: can't determine Catalog's flavor."
	echo "       Please set it in /etc/bacula/bacula_flavor and try again."
	exit 1
fi

cd $WORKDIR
rm -f $DATAFILE


case "$FLAVOR" in
	"sqlite")
		# remove "$*" from cmdline -- by mechanix@debian.org
		echo ".dump" | /usr/bin/sqlite bacula.db > $DATAFILE
	;;

	"mysql")
		/usr/bin/mysqldump $* -f --opt bacula > $DATAFILE
	;;

	"pgsql")
		/usr/bin/pg_dump $* bacula > $DATAFILE
	;;
esac

#
#  To read back a MySQL database use: 
#     cd /var/lib/bacula
#     rm -f /../var/bacula/*
#     mysql <bacula.sql
#
#  To read back a SQLite database use:
#     cd /var/lib/bacula
#     rm -f bacula.db
#     sqlite bacula.db <bacula.sql
#
#  To read back a PostgreSQL database use:
#     cd /var/lib/bacula
#     dropdb bacula
#     psql bacula <bacula.sql
#

exit 0
