debian/tmp-install-sqlite/usr/sbin/bsmtp		usr/lib/bacula
debian/tmp-install-sqlite/etc/bacula/scripts/query.sql etc/bacula/scripts
debian/tmp-install-sqlite/usr/sbin/btraceback usr/lib/bacula
debian/tmp-install-sqlite/etc/bacula/scripts/btraceback.gdb etc/bacula/scripts
debian/tmp-install-sqlite/usr/sbin/bwild usr/sbin
debian/tmp-install-sqlite/usr/sbin/bregex usr/sbin
debian/additions/postinst-common	usr/share/bacula-director
