debian/tmp-install-sqlite/usr/sbin/bacula-sd usr/sbin
debian/tmp-install-sqlite/usr/sbin/bls       usr/sbin
debian/tmp-install-sqlite/usr/sbin/bextract  usr/sbin
debian/tmp-install-sqlite/usr/sbin/btape     usr/sbin
debian/tmp-install-sqlite/etc/bacula/scripts/mtx-changer etc/bacula/scripts
debian/tmp-install-sqlite/etc/bacula/scripts/disk-changer etc/bacula/scripts
debian/tmp-install-sqlite/etc/bacula/scripts/dvd-handler etc/bacula/scripts
