etc/bacula/scripts/make_postgresql_tables	usr/share/bacula-director
etc/bacula/scripts/grant_postgresql_privileges usr/share/bacula-director
etc/bacula/scripts/update_postgres* usr/share/bacula-director
etc/bacula/scripts/*catalog_backup etc/bacula/scripts
etc/bacula/scripts/*catalog_backup.pl etc/bacula/scripts
usr/sbin/bacula-dir                  usr/sbin
usr/sbin/dbcheck                  usr/sbin
debian/additions/pgsql	usr/share/dbconfig-common/data/bacula-director-pgsql/install-dbadmin
