#!/bin/sh
#
# First script called by Linux when booting
#

trap "" 1 2 3 15
exec >/dev/console </dev/console 2>&1
mount -t proc none /proc

CMDLINE=`cat /proc/cmdline`
DEBUG=""
case "$CMDLINE" in *debug*) DEBUG="yes"; ;; esac
export DEBUG

# Magic incantation for root to remain in ram 
echo 0x0100 > /proc/sys/kernel/real-root-dev

mount -o remount,rw /dev/root /

# sh

exit 0
