#!/bin/sh

echo "Start sysinit ..."

PATH="/sbin:/usr/sbin:/bin:/usr/bin:/usr/X11R6/bin"
export PATH

echo "Remounting root filesystem read-write"
mount -o remount,rw /dev/root /

mount -t proc none /proc
mount -t devpts none /dev/pts

touch  /var/run/utmp /var/run/wtmp /var/log/wtmp
chgrp utmp /var/run/utmp /var/log/wtmp
chmod 0664 /var/run/utmp /var/log/wtmp

syslogd -m 0
klogd -x 

echo "Attempting to mount CDDOM..."
/etc/mount_cdrom

echo "Loading the ethernet driver module"
/etc/load_eth0

ifconfig lo 127.0.0.1 netmask 255.0.0.0 up

/bin/hostname RescueCD

echo "Boot complete."
sleep 3 # give time to read messages
