/* Automatically generated by po2tbl.sed from bacula.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"_New File", 2},
  {"Bacula", 3},
  {"Connect", 4},
  {"New File", 5},
  {"Open", 6},
  {"Open File", 7},
  {"Save", 8},
  {"Save File", 9},
  {"label1", 10},
  {"Copyright (c) 1999 - 2002, Kern Sibbald and John Walker", 11},
  {"It comes by night and sucks the essence from your computers.", 12},
  {"Couldn't find pixmap file: %s", 13},
  {"Couldn't create pixmap from file: %s", 14},
};

int _msg_tbl_length = 14;
