#!/bin/sh
#
# Make full release
#
branch=5.0.0
#
# Bacula git repos
bacula=/home/kern/bacula/k
docs=/home/kern/bacula/docs
rescue=/home/kern/bacula/rescue
export push=yes
export updatepo=yes

./makeclean
./makebacularel $bacula $branch
./makedocsrel $bacula $docs $branch
./makerescuerel $rescue $branch
./makewinrel $bacula $branch | tee win$$.log

grep -i warning win$$.log >/dev/null
if [ $? -eq 0 ] ; then
  echo " "
  echo "Warnings in win$$.log"
  exit 1
fi
grep -i error win$$.log >/dev/null
if [ $? -eq 0 ] ; then
  echo " "
  echo "Errors in win$$.log"
  exit 1
fi
rm -f win$$.log
