#!/bin/sh
rm -f 1
touch 1
for i in . console gnome2-console cats dird filed tray-monitor \
     qt-console \
     win32 win32/compat findlib lib wx-console stored tools \
     win32/wx-console win32/console win32/baculafd win32/filed \
     win32/dird win32/libwin32 win32/stored win32/stored/baculasd \
     tray-monitor qt-console qt-console/clients qt-console/console \
     qt-console/fileset qt-console/help qt-console/jobgraphs \
     qt-console/joblist qt-console/joblog qt-console/jobs qt-console/label \
     qt-console/mediaedit qt-console/medialist qt-console/mount \
     qt-console/relabel qt-console/restore qt-console/run qt-console/select \
     qt-console/storage; do
  ls -1 $i/*.c $i/*.cpp $i/*.h $i/*.in 2>/dev/null >>1
done
cat 1 | $HOME/bin/lines
# rm -f 1
