.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH BACULA\-SD 8 "Jan 24, 2004" "Kern Sibbald" "Network backup, recovery & verification"
.\" Please adjust this date whenever revising the manpage.
.\"
.SH NAME
.B bacula\-sd
\- Bacula's Storage Daemon
.SH SYNOPSIS
.B bacula\-sd
.RI [ options ]
.br
.SH DESCRIPTION
This manual page documents briefly the
.B bacula\-sd
command.
This manual page was written for the Debian distribution
because the original program does not have a manual page.
.br
Bacula's Storage Daemon acts as the interface between the Bacula
network backup system and a tape drive/autochanger or filesystem where
the backups will be stored.
.SH OPTIONS
.TP
.B \-c\  config
Change location to read \fIbacula\-sd.conf\fP from (default $CWD)
.TP
.BI \-u\  user
Set the username/uid to run as.
.TP
.BI \-g\  group
Set the group/gid to run as.
.SH SEE ALSO
.BR bacula\-dir (8),
.BR bacula\-fd (8),
.BR bacula (8).
.br
.SH AUTHOR
This manual page was written by Jose Luis Tallon
.nh
<jltallon@adv\-solutions.net>,
for the Debian GNU/Linux system (but may be used by others).
