.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH BACULA\-DIR 8 "Jan 24, 2004" "Kern Sibbald" "Network backup, recovery&verification"
.\" Please adjust this date whenever revising the manpage.
.\"
.SH NAME
.B bacula\-dir
\- Bacula Director
.SH SYNOPSIS
.B bacula\-dir
.RI [ options ]
.br
.SH DESCRIPTION
This manual page documents briefly the
.B bacula\-dir
command.
This manual page was written for the Debian distribution
because the original program does not have a manual page.
.br
Bacula's Director Daemon acts as the controller of the
network backup system: it is responsible for scheduling and 
coordinating backups across the network.
.SH OPTIONS
.TP
.BI \-c
Change location to read \fIbacula-dir.conf\fP from (default $CWD)
.TP
.BI \-u
Set the username/uid to run as.
.TP
.BI \-g
Set the group/gid to run as.
.SH SEE ALSO
.BR bacula-fd (8),
.BR bacula-sd (8).
.br
.SH AUTHOR
This manual page was written by Jose Luis Tallon
.nh
<jltallon@adv\-solutions.net>,
for the Debian GNU/Linux system (but may be used by others).

