.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH CONSOLE 8 "Oct 24, 2003" "Kern Sibbald&John Walker" "Network backup, recovery and verification"
.\" Please adjust this date whenever revising the manpage.
.\"
.SH NAME
 console \- Bacula's management Console
.SH SYNOPSIS
.B console
.RI [options]
.br
.SH DESCRIPTION
This manual page documents briefly the
.B console
command.
This manual page was written for the Debian distribution
because the original program does not have a manual page.
.PP
.SH OPTIONS
.TP
.BI \-c\  config
Specify configuration file.
.TP
.BI \-d\  nn
Set debug level to \fInn\fP.
.TP
.B \-s
No signals.
.TP
.B \-t
Test config mode: read configuration and exit.
.TP
.B \-?
Show version and usage of program.
.SH SEE ALSO
.BR bacula\-dir (8),
.BR bls (1),
.BR bextract (1).
.br
.SH AUTHOR
This manual page was written by Jose Luis Tallon
.nh 
<jltallon@adv\-solutions.net>,
for the Debian GNU/Linux system (but may be used by others).
