.\"                                      Hey, EMACS: -*- nroff -*-
.TH BACULA\-SMTP 1 "Jan 24, 2004" "Kern Sibbald" "Network backup"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
 smtp \- Bacula's SMTP helper
.SH DESCRIPTION
This manual page was written for the Debian distribution
because the original program does not have a manual page.
.br
.SH AUTHOR
This manual page was written by Jose Luis Tallon
.nh 
<jltallon@adv\-solutions.net>,
for the Debian GNU/Linux system (but may be used by others).
